import { ApiClientError } from '../api/apiError';
import { reportCardDocumentFilename } from '../../utils/reportCardGeneration';
import { publishedResultRepository } from '../marksResult/publishedResultRepository';
import { reportCardRepository } from './reportCardRepository';
import type { ReportCardDocumentService } from './reportCardDocumentService';
const success = <T>(data: T, message: string) => ({
  data,
  message,
  success: true,
});
const cardFor = (schoolId: string, id: string) =>
  reportCardRepository
    .cards()
    .find(item => item.id === id && item.schoolId === schoolId) ??
  (() => {
    throw new ApiClientError({
      code: 'REPORT_CARD_NOT_FOUND',
      message: 'Report Card was not found.',
      status: 404,
    });
  })();
const resultFor = (card: ReturnType<typeof cardFor>) => ({
  documentStatus: card.documentStatus,
  documentUrl: card.documentUrl,
  expiresAt: card.documentExpiresAt,
  filename: reportCardDocumentFilename(
    card.reportCardNumber,
    card.studentSnapshot.name,
  ),
  isDevelopmentMock: true,
  message:
    'Development preview metadata only; the authoritative PDF will be generated by the Python backend.',
  reportCardId: card.id,
});
export const mockReportCardDocumentService: ReportCardDocumentService = {
  async getDocumentStatus(schoolId, id) {
    const card = cardFor(schoolId, id);
    if (
      card.status === 'REVOKED' ||
      !publishedResultRepository
        .list()
        .some(
          item =>
            item.id === card.publishedResultSnapshotId &&
            item.status === 'PUBLISHED',
        )
    )
      throw new ApiClientError({
        code: 'REPORT_CARD_DOCUMENT_UNAVAILABLE',
        message: 'This Report Card document is no longer available.',
        status: 410,
      });
    return success(resultFor(card), 'Development document status loaded.');
  },
  async requestDocument(schoolId, id) {
    const card = cardFor(schoolId, id);
    if (card.status === 'REVOKED')
      throw new ApiClientError({
        code: 'REPORT_CARD_REVOKED',
        message: 'Revoked Report Cards cannot request a document.',
        status: 410,
      });
    if (card.documentStatus === 'DOCUMENT_FAILED')
      return success(
        resultFor(card),
        'Development document generation remains failed.',
      );
    card.documentStatus = 'PREVIEW_READY';
    card.documentUrl = `development://report-cards/${card.id}/preview`;
    card.updatedAt = new Date().toISOString();
    return success(
      resultFor(card),
      'Development Report Card preview is ready.',
    );
  },
};
