import type {
  FeeDue,
  FeeDueActivity,
  FeeDueWaiver,
  FeeGenerationRun,
  FineRuleSnapshot,
  FineWaiver,
} from '../../models/feeDue';
import { calculateOutstandingAmount } from '../../utils/feeOutstandingCalculation';

const generatedAt = '2026-07-20T10:00:00.000Z';
const schoolId = 'school-omt';

export const DAILY_FINE_SNAPSHOT: FineRuleSnapshot = {
  code: 'DAY10',
  dailyAmountPaise: 1_000,
  graceDays: 3,
  id: 'fine-daily',
  maximumAmountPaise: 30_000,
  name: 'Daily Late Fine',
  type: 'DAILY_AFTER_DUE',
};
export const FIXED_FINE_SNAPSHOT: FineRuleSnapshot = {
  code: 'FIX50',
  fixedAmountPaise: 5_000,
  graceDays: 0,
  id: 'fine-fixed',
  name: 'Fixed Late Fine',
  type: 'FIXED_AFTER_DUE',
};
export const SLAB_FINE_SNAPSHOT: FineRuleSnapshot = {
  code: 'SLAB',
  graceDays: 0,
  id: 'fine-slab',
  name: 'Slab Late Fine',
  slabs: [
    { amountPaise: 5_000, fromDay: 1, toDay: 10 },
    { amountPaise: 10_000, fromDay: 11, toDay: 20 },
    { amountPaise: 20_000, fromDay: 21 },
  ],
  type: 'SLAB_BASED',
};

function due(
  id: string,
  patch: Partial<FeeDue> & Pick<FeeDue, 'studentId' | 'enrollmentId' | 'feeAssignmentId'>,
): FeeDue {
  const status = patch.status ?? 'PENDING';
  const base: FeeDue = {
    academicSessionId: 'session-school-omt-current',
    admissionNumberSnapshot: 'OMT-2026-0001',
    baseAmountPaise: 80_000,
    branchId: 'branch-main',
    branchNameSnapshot: 'Main Branch',
    calculationSnapshot: {
      applicability: 'ALL_STUDENTS',
      discountNames: [],
      dueRule: { day: 10, type: 'FIXED_DAY_OF_PERIOD' },
      feeStructureItemId: 'fee-structure-c01-active-tuition',
      feeStructureName: 'Class 1 Standard Fees',
      frequency: 'MONTHLY',
      generatedAsOfDate: '2026-07-20',
      mandatory: true,
      overrideType: 'DEFAULT_AMOUNT',
      selected: true,
      warnings: [],
    },
    classNameSnapshot: 'Class 1',
    createdAt: generatedAt,
    discountAmountPaise: 0,
    dueDate: '2026-07-10',
    enrollmentId: patch.enrollmentId,
    exemptionAmountPaise: 0,
    feeAssignmentId: patch.feeAssignmentId,
    feeHeadCodeSnapshot: 'TUI',
    feeHeadId: 'fee-head-tuition',
    feeHeadNameSnapshot: 'Tuition Fee',
    feeStructureId: 'fee-structure-c01-active',
    feeStructureItemId: 'fee-structure-c01-active-tuition',
    fineAmountPaise: 0,
    fineWaivedAmountPaise: 0,
    frequencySnapshot: 'MONTHLY',
    generatedAt,
    generatedByRunId: 'fee-run-july',
    id,
    netFeeAmountPaise: 80_000,
    outstandingAmountPaise: 80_000,
    overrideAmountPaise: 0,
    paidAmountPaise: 0,
    periodKey: '2026-07',
    periodLabel: 'July 2026',
    periodType: 'MONTH',
    schoolId,
    sectionNameSnapshot: 'Section A',
    status,
    studentId: patch.studentId,
    studentNameSnapshot: 'Rahul Patel',
    updatedAt: generatedAt,
  };
  const result = { ...base, ...patch };
  result.calculationSnapshot = {
    ...result.calculationSnapshot,
    feeStructureItemId: result.feeStructureItemId,
    frequency: result.frequencySnapshot,
  };
  result.outstandingAmountPaise = calculateOutstandingAmount(result);
  return result;
}

export const INITIAL_FEE_DUES: FeeDue[] = [
  due('due-rahul-august', {
    dueDate: '2026-08-10',
    enrollmentId: 'enrollment-student-rahul-current',
    feeAssignmentId: 'fee-assignment-rahul',
    periodKey: '2026-08',
    periodLabel: 'August 2026',
    status: 'UPCOMING',
    studentId: 'student-rahul',
  }),
  due('due-rahul-july-pending', {
    dueDate: '2026-07-31',
    enrollmentId: 'enrollment-student-rahul-current',
    feeAssignmentId: 'fee-assignment-rahul',
    periodKey: '2026-07-PENDING',
    periodLabel: 'July 2026 · Pending',
    status: 'PENDING',
    studentId: 'student-rahul',
  }),
  due('due-rahul-june-daily', {
    dueDate: '2026-06-10',
    enrollmentId: 'enrollment-student-rahul-current',
    feeAssignmentId: 'fee-assignment-rahul',
    fineAmountPaise: 30_000,
    fineCalculatedThrough: '2026-07-31',
    fineRuleSnapshot: DAILY_FINE_SNAPSHOT,
    periodKey: '2026-06',
    periodLabel: 'June 2026',
    status: 'OVERDUE',
    studentId: 'student-rahul',
  }),
  due('due-aarav-admission', {
    baseAmountPaise: 100_000,
    classNameSnapshot: 'Class 2',
    discountAmountPaise: 10_000,
    dueDate: '2026-04-15',
    enrollmentId: 'enrollment-student-aarav-current',
    feeAssignmentId: 'fee-assignment-aarav',
    feeHeadCodeSnapshot: 'ADM',
    feeHeadId: 'fee-head-admission',
    feeHeadNameSnapshot: 'Admission Fee',
    feeStructureId: 'fee-structure-c02-active',
    feeStructureItemId: 'fee-structure-c02-active-admission',
    fineAmountPaise: 5_000,
    fineCalculatedThrough: '2026-07-31',
    fineRuleSnapshot: FIXED_FINE_SNAPSHOT,
    frequencySnapshot: 'ONE_TIME',
    netFeeAmountPaise: 90_000,
    periodKey: 'ONE_TIME-FEE-HEAD-ADMISSION',
    periodLabel: 'Admission Fee',
    periodType: 'ONE_TIME',
    status: 'OVERDUE',
    studentId: 'student-aarav',
    studentNameSnapshot: 'Aarav Kumar',
  }),
  due('due-aarav-quarter', {
    baseAmountPaise: 240_000,
    classNameSnapshot: 'Class 2',
    dueDate: '2026-04-10',
    enrollmentId: 'enrollment-student-aarav-current',
    feeAssignmentId: 'fee-assignment-aarav',
    frequencySnapshot: 'QUARTERLY',
    netFeeAmountPaise: 240_000,
    periodKey: '2026-27-Q1',
    periodLabel: 'Quarter 1',
    periodType: 'QUARTER',
    status: 'OVERDUE',
    studentId: 'student-aarav',
    studentNameSnapshot: 'Aarav Kumar',
  }),
  due('due-rahul-half-year', {
    baseAmountPaise: 480_000,
    dueDate: '2026-04-10',
    enrollmentId: 'enrollment-student-rahul-current',
    feeAssignmentId: 'fee-assignment-rahul',
    frequencySnapshot: 'HALF_YEARLY',
    netFeeAmountPaise: 480_000,
    periodKey: '2026-27-H1',
    periodLabel: 'Half-Year 1',
    periodType: 'HALF_YEAR',
    status: 'OVERDUE',
    studentId: 'student-rahul',
  }),
  due('due-rahul-year', {
    baseAmountPaise: 5_000,
    dueDate: '2026-04-10',
    enrollmentId: 'enrollment-student-rahul-current',
    feeAssignmentId: 'fee-assignment-rahul',
    feeHeadCodeSnapshot: 'LIB',
    feeHeadId: 'fee-head-library',
    feeHeadNameSnapshot: 'Library Fee',
    frequencySnapshot: 'YEARLY',
    netFeeAmountPaise: 5_000,
    periodKey: '2026-27',
    periodLabel: '2026-27',
    periodType: 'YEAR',
    status: 'OVERDUE',
    studentId: 'student-rahul',
  }),
  due('due-rahul-installment', {
    baseAmountPaise: 20_000,
    dueDate: '2026-09-10',
    enrollmentId: 'enrollment-student-rahul-current',
    feeAssignmentId: 'fee-assignment-rahul',
    installmentNumber: 1,
    netFeeAmountPaise: 20_000,
    periodKey: 'INST-1',
    periodLabel: 'Installment 1',
    periodType: 'INSTALLMENT',
    status: 'UPCOMING',
    studentId: 'student-rahul',
  }),
  due('due-rahul-slab-waiver', {
    dueDate: '2026-07-01',
    enrollmentId: 'enrollment-student-rahul-current',
    feeAssignmentId: 'fee-assignment-rahul',
    fineAmountPaise: 20_000,
    fineCalculatedThrough: '2026-07-31',
    fineRuleSnapshot: SLAB_FINE_SNAPSHOT,
    fineWaivedAmountPaise: 5_000,
    periodKey: '2026-05-SLAB',
    periodLabel: 'May 2026 · Slab Fine',
    status: 'OVERDUE',
    studentId: 'student-rahul',
  }),
  due('due-myra-waived', {
    enrollmentId: 'enrollment-student-myra-current',
    exemptionAmountPaise: 80_000,
    feeAssignmentId: 'fee-assignment-myra',
    netFeeAmountPaise: 0,
    periodKey: '2026-04-WAIVED',
    periodLabel: 'April 2026',
    status: 'WAIVED',
    studentId: 'student-myra',
    studentNameSnapshot: 'Myra Shah',
    waivedAt: '2026-07-21T10:00:00.000Z',
    waivedByUserId: 'user-school-admin',
    waiverReason: 'Approved full fee waiver',
  }),
  due('due-rahul-cancelled', {
    cancellationReason: 'Generated against incorrect period',
    cancelledAt: '2026-07-22T10:00:00.000Z',
    cancelledByUserId: 'user-school-admin',
    enrollmentId: 'enrollment-student-rahul-current',
    feeAssignmentId: 'fee-assignment-rahul',
    periodKey: '2026-04-CANCELLED',
    periodLabel: 'April 2026',
    status: 'CANCELLED',
    studentId: 'student-rahul',
  }),
  due('due-rahul-closed-history', {
    academicSessionId: 'session-school-omt-closed',
    classNameSnapshot: 'Class 5',
    dueDate: '2025-07-10',
    enrollmentId: 'enrollment-student-rahul-previous',
    feeAssignmentId: 'fee-assignment-rahul-historical',
    feeStructureId: 'fee-structure-c05-closed',
    feeStructureItemId: 'fee-structure-c05-closed-tuition',
    periodKey: '2025-07',
    periodLabel: 'July 2025',
    status: 'OVERDUE',
    studentId: 'student-rahul',
  }),
  due('due-arjun-self', {
    classNameSnapshot: 'Class 4',
    enrollmentId: 'enrollment-student-arjun-current',
    feeAssignmentId: 'fee-assignment-arjun-snapshot',
    feeStructureId: 'fee-structure-arjun-snapshot',
    feeStructureItemId: 'fee-structure-arjun-snapshot-tuition',
    periodKey: '2026-08-ARJUN',
    periodLabel: 'August 2026',
    status: 'UPCOMING',
    studentId: 'student-arjun',
    studentNameSnapshot: 'Arjun Nair',
  }),
];

export const INITIAL_FEE_GENERATION_RUNS: FeeGenerationRun[] = [
  {
    academicSessionId: 'session-school-omt-current',
    academicSessionName: '2026-27',
    branchId: 'branch-main',
    branchName: 'Main Branch',
    classIds: ['class-omt-c01', 'class-omt-c02'],
    completedAt: generatedAt,
    createdAt: generatedAt,
    createdCount: 8,
    existingCount: 1,
    failedCount: 0,
    feeHeadIds: [],
    generationType: 'CLASS',
    id: 'fee-run-july',
    requestedAt: generatedAt,
    requestedByUserId: 'user-school-admin',
    requestedPeriods: ['2026-07'],
    schoolId,
    sectionIds: [],
    skippedCount: 2,
    status: 'COMPLETED',
    studentIds: [],
    totalCandidates: 11,
    totalGeneratedAmountPaise: 720_000,
  },
  {
    academicSessionId: 'session-school-omt-closed',
    academicSessionName: '2025-26',
    branchId: 'branch-main',
    branchName: 'Main Branch',
    classIds: ['class-omt-closed-c05'],
    completedAt: '2025-07-01T10:00:00.000Z',
    createdAt: '2025-07-01T10:00:00.000Z',
    createdCount: 1,
    existingCount: 0,
    failedCount: 0,
    feeHeadIds: ['fee-head-tuition'],
    generationType: 'CLASS',
    id: 'fee-run-closed',
    requestedAt: '2025-07-01T10:00:00.000Z',
    requestedByUserId: 'user-school-admin',
    requestedPeriods: ['2025-07'],
    schoolId,
    sectionIds: [],
    skippedCount: 0,
    status: 'COMPLETED',
    studentIds: ['student-rahul'],
    totalCandidates: 1,
    totalGeneratedAmountPaise: 80_000,
  },
];

export const INITIAL_FINE_WAIVERS: FineWaiver[] = [
  {
    amountPaise: 5_000,
    approvedAt: '2026-07-25T10:00:00.000Z',
    approvedByUserId: 'user-school-admin',
    feeDueId: 'due-rahul-slab-waiver',
    id: 'fine-waiver-rahul',
    reason: 'Approved hardship correction',
    type: 'PARTIAL_FINE',
  },
];

export const INITIAL_DUE_WAIVERS: FeeDueWaiver[] = [
  {
    approvedAt: '2026-07-21T10:00:00.000Z',
    approvedByUserId: 'user-school-admin',
    feeDueId: 'due-myra-waived',
    id: 'due-waiver-myra',
    reason: 'Approved full fee waiver',
  },
];

export const INITIAL_FEE_DUE_ACTIVITIES: FeeDueActivity[] = INITIAL_FEE_DUES.map(
  item => ({
    academicSessionId: item.academicSessionId,
    action: 'FEE_DUE_CREATED',
    branchId: item.branchId,
    feeDueId: item.id,
    generationRunId: item.generatedByRunId,
    id: `activity-created-${item.id}`,
    performedAt: item.generatedAt,
    performedByUserId: 'user-school-admin',
    schoolId: item.schoolId,
    studentId: item.studentId,
  }),
);
