import type {
  DiscountDefinition,
  FeeHead,
  FeeStructure,
  FineRule,
  StudentFeeAssignment,
} from '../../models/fee';

const schoolId = 'school-omt';
const timestamp = '2026-07-20T10:00:00.000Z';

const headData = [
  ['tuition', 'Tuition Fee', 'TUI', 'RECURRING', 'MONTHLY', true, false],
  ['admission', 'Admission Fee', 'ADM', 'ONE_TIME', 'ONE_TIME', true, false],
  ['transport', 'Transport Fee', 'TRN', 'RECURRING', 'MONTHLY', false, false],
  ['exam', 'Examination Fee', 'EXM', 'ONE_TIME', 'ONE_TIME', true, false],
  ['computer', 'Computer Fee', 'COM', 'RECURRING', 'MONTHLY', false, false],
  ['library', 'Library Fee', 'LIB', 'RECURRING', 'YEARLY', true, true],
  ['development', 'Development Fee', 'DEV', 'ONE_TIME', 'ONE_TIME', true, false],
  ['sports', 'Sports Fee', 'SPT', 'RECURRING', 'YEARLY', false, false],
  ['hostel', 'Hostel Fee', 'HST', 'RECURRING', 'MONTHLY', false, true],
  ['custom', 'Custom Fee', 'CUS', 'ONE_TIME', 'ONE_TIME', false, false],
] as const;

export const INITIAL_FEE_HEADS: FeeHead[] = headData.map(
  ([slug, name, code, type, defaultFrequency, mandatory, refundable], index) => ({
    activeStructureItemCount: index < 7 ? 2 : 0,
    code,
    createdAt: timestamp,
    defaultFrequency,
    displayOrder: index + 1,
    id: `fee-head-${slug}`,
    mandatoryByDefault: mandatory,
    name,
    refundable,
    schoolId,
    status: slug === 'custom' ? 'INACTIVE' : 'ACTIVE',
    type,
    updatedAt: timestamp,
  }),
);

const monthlyMonths = [4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3];

function structure(
  id: string,
  classCode: string,
  status: FeeStructure['status'],
  overrides: Partial<FeeStructure> = {},
): FeeStructure {
  const items: FeeStructure['items'] = [
    {
      amount: 800,
      applicability: 'ALL_STUDENTS' as const,
      applicableMonths: monthlyMonths,
      displayOrder: 1,
      dueRule: { day: 10, type: 'FIXED_DAY_OF_PERIOD' as const },
      feeHeadId: 'fee-head-tuition',
      feeHeadName: 'Tuition Fee',
      feeStructureId: id,
      frequency: 'MONTHLY' as const,
      id: `${id}-tuition`,
      mandatory: true,
      status: 'ACTIVE' as const,
    },
    {
      amount: 300,
      applicability: 'OPTIONAL_SELECTION' as const,
      applicableMonths: monthlyMonths,
      displayOrder: 2,
      dueRule: { day: 10, type: 'FIXED_DAY_OF_PERIOD' as const },
      feeHeadId: 'fee-head-transport',
      feeHeadName: 'Transport Fee',
      feeStructureId: id,
      fineRuleId: 'fine-daily',
      frequency: 'MONTHLY' as const,
      id: `${id}-transport`,
      mandatory: false,
      status: 'ACTIVE' as const,
    },
    {
      amount: 1000,
      applicability: 'ALL_STUDENTS' as const,
      displayOrder: 3,
      dueRule: { date: '2026-04-15', type: 'FIXED_DATE' as const },
      feeHeadId: 'fee-head-admission',
      feeHeadName: 'Admission Fee',
      feeStructureId: id,
      frequency: 'ONE_TIME' as const,
      id: `${id}-admission`,
      mandatory: true,
      status: 'ACTIVE' as const,
    },
  ];
  if (id === 'fee-structure-c02-active') {
    items.push(
      {
        amount: 2400,
        applicability: 'ALL_STUDENTS',
        displayOrder: 4,
        dueRule: { day: 10, type: 'FIXED_DAY_OF_PERIOD' },
        feeHeadId: 'fee-head-computer',
        feeHeadName: 'Computer Fee',
        feeStructureId: id,
        frequency: 'QUARTERLY',
        id: `${id}-examination`,
        mandatory: true,
        status: 'ACTIVE',
      },
      {
        amount: 500,
        applicability: 'ALL_STUDENTS',
        displayOrder: 5,
        dueRule: { day: 10, type: 'FIXED_DAY_OF_PERIOD' },
        feeHeadId: 'fee-head-library',
        feeHeadName: 'Library Fee',
        feeStructureId: id,
        frequency: 'HALF_YEARLY',
        id: `${id}-library`,
        mandatory: true,
        status: 'ACTIVE',
      },
      {
        amount: 900,
        applicability: 'ALL_STUDENTS',
        displayOrder: 6,
        dueRule: { day: 10, type: 'FIXED_DAY_OF_PERIOD' },
        feeHeadId: 'fee-head-sports',
        feeHeadName: 'Sports Fee',
        feeStructureId: id,
        frequency: 'YEARLY',
        id: `${id}-sports`,
        mandatory: true,
        status: 'ACTIVE',
      },
      {
        amount: 3000,
        applicability: 'ALL_STUDENTS',
        displayOrder: 7,
        dueRule: { day: 10, type: 'FIXED_DAY_OF_PERIOD' },
        feeHeadId: 'fee-head-hostel',
        feeHeadName: 'Hostel Fee',
        feeStructureId: id,
        frequency: 'YEARLY',
        id: `${id}-hostel-installments`,
        installmentCount: 3,
        mandatory: true,
        status: 'ACTIVE',
      },
    );
  }
  if (id === 'fee-structure-c01-inactive') {
    items.push({
      amount: 200,
      applicability: 'MANUAL_ASSIGNMENT',
      displayOrder: 4,
      dueRule: { date: '2026-04-15', type: 'FIXED_DATE' as const },
      feeHeadId: 'fee-head-custom',
      feeHeadName: 'Custom Fee',
      feeStructureId: id,
      frequency: 'ONE_TIME',
      id: `${id}-custom`,
      mandatory: false,
      status: 'INACTIVE',
    });
  }
  return {
    academicSessionId: 'session-school-omt-current',
    academicSessionName: '2026-27',
    assignedStudentCount: status === 'ACTIVE' ? 2 : 0,
    branchId: 'branch-main',
    branchName: 'Main Branch',
    classId: `class-omt-${classCode}`,
    className: `Class ${Number(classCode.slice(1))}`,
    createdAt: timestamp,
    effectiveFrom: '2026-04-01',
    id,
    items,
    name: `Class ${Number(classCode.slice(1))} Standard Fees`,
    schoolId,
    status,
    totalNominalAmount: items.reduce((sum, item) => sum + item.amount, 0),
    updatedAt: timestamp,
    ...overrides,
  };
}

export const INITIAL_FEE_STRUCTURES: FeeStructure[] = [
  structure('fee-structure-c01-active', 'c01', 'ACTIVE'),
  structure('fee-structure-c02-active', 'c02', 'ACTIVE'),
  structure('fee-structure-c03-draft', 'c03', 'DRAFT'),
  structure('fee-structure-c01-inactive', 'c01', 'INACTIVE', {
    effectiveFrom: '2025-04-01',
    name: 'Class 1 Historical Fees',
  }),
  structure('fee-structure-c05-closed', 'c05', 'INACTIVE', {
    academicSessionId: 'session-school-omt-closed',
    academicSessionName: '2025-26',
    effectiveFrom: '2025-04-01',
    name: 'Class 5 Closed Session Fees',
  }),
];

export const INITIAL_DISCOUNTS: DiscountDefinition[] = [
  {
    activeAssignmentCount: 1,
    applicableFeeHeadIds: ['fee-head-tuition'],
    category: 'SCHOLARSHIP',
    code: 'SCH20',
    createdAt: timestamp,
    id: 'discount-scholarship',
    maximumAmount: 300,
    name: 'Scholarship 20%',
    reasonRequired: true,
    schoolId,
    startDate: '2026-04-01',
    status: 'ACTIVE',
    type: 'PERCENTAGE',
    updatedAt: timestamp,
    value: 20,
  },
  {
    activeAssignmentCount: 1,
    applicableFeeHeadIds: [],
    category: 'SIBLING',
    code: 'SIB100',
    createdAt: timestamp,
    id: 'discount-sibling',
    name: 'Sibling Discount',
    reasonRequired: false,
    schoolId,
    startDate: '2026-04-01',
    status: 'ACTIVE',
    type: 'FIXED',
    updatedAt: timestamp,
    value: 100,
  },
];

export const INITIAL_FINE_RULES: FineRule[] = [
  {
    activeUsageCount: 0,
    code: 'FIX50',
    createdAt: timestamp,
    fixedAmount: 50,
    graceDays: 0,
    id: 'fine-fixed',
    name: 'Fixed Late Fine',
    schoolId,
    status: 'ACTIVE',
    type: 'FIXED_AFTER_DUE',
    updatedAt: timestamp,
  },
  {
    activeUsageCount: 1,
    code: 'DAY10',
    createdAt: timestamp,
    dailyAmount: 10,
    graceDays: 3,
    id: 'fine-daily',
    maximumAmount: 300,
    name: 'Daily Late Fine',
    schoolId,
    status: 'ACTIVE',
    type: 'DAILY_AFTER_DUE',
    updatedAt: timestamp,
  },
  {
    activeUsageCount: 0,
    code: 'SLAB',
    createdAt: timestamp,
    graceDays: 0,
    id: 'fine-slab',
    name: 'Slab Late Fine',
    schoolId,
    slabs: [
      { amount: 50, fromDay: 1, toDay: 10 },
      { amount: 100, fromDay: 11, toDay: 20 },
      { amount: 200, fromDay: 21 },
    ],
    status: 'ACTIVE',
    type: 'SLAB_BASED',
    updatedAt: timestamp,
  },
];

export const INITIAL_FEE_ASSIGNMENTS: StudentFeeAssignment[] = [
  {
    amountOverrides: [],
    createdAt: timestamp,
    discountAssignments: [],
    effectiveFrom: '2026-04-01',
    enrollmentId: 'enrollment-student-rahul-current',
    feeStructureId: 'fee-structure-c01-active',
    id: 'fee-assignment-rahul',
    optionalItemSelections: [
      {
        effectiveFrom: '2026-04-01',
        feeStructureItemId: 'fee-structure-c01-active-transport',
        selected: true,
      },
    ],
    schoolId,
    status: 'ACTIVE',
    studentId: 'student-rahul',
    updatedAt: timestamp,
  },
  {
    amountOverrides: [
      {
        createdAt: timestamp,
        customAmount: 500,
        effectiveFrom: '2026-04-01',
        feeStructureItemId: 'fee-structure-c02-active-transport',
        id: 'override-aarav-transport',
        reason: 'Long-distance route',
        type: 'CUSTOM_AMOUNT',
      },
    ],
    createdAt: timestamp,
    discountAssignments: [
      {
        approvedByUserId: 'user-school-admin',
        createdAt: timestamp,
        discountDefinitionId: 'discount-sibling',
        effectiveFrom: '2026-04-01',
        feeHeadIds: [],
        id: 'student-discount-aarav',
        status: 'ACTIVE',
        studentFeeAssignmentId: 'fee-assignment-aarav',
      },
    ],
    effectiveFrom: '2026-04-01',
    enrollmentId: 'enrollment-student-aarav-current',
    feeStructureId: 'fee-structure-c02-active',
    id: 'fee-assignment-aarav',
    optionalItemSelections: [
      {
        effectiveFrom: '2026-04-01',
        feeStructureItemId: 'fee-structure-c02-active-transport',
        selected: true,
      },
    ],
    schoolId,
    status: 'ACTIVE',
    studentId: 'student-aarav',
    updatedAt: timestamp,
  },
  {
    amountOverrides: [
      {
        createdAt: timestamp,
        effectiveFrom: '2026-04-01',
        feeStructureItemId: 'fee-structure-c01-active-admission',
        id: 'override-myra-admission-exempt',
        reason: 'Approved admission fee waiver',
        type: 'EXEMPT',
      },
    ],
    createdAt: timestamp,
    discountAssignments: [],
    effectiveFrom: '2026-04-01',
    enrollmentId: 'enrollment-student-myra-current',
    feeStructureId: 'fee-structure-c01-active',
    id: 'fee-assignment-myra',
    optionalItemSelections: [
      {
        effectiveFrom: '2026-04-01',
        feeStructureItemId: 'fee-structure-c01-active-transport',
        selected: false,
      },
    ],
    schoolId,
    status: 'ACTIVE',
    studentId: 'student-myra',
    updatedAt: timestamp,
  },
  {
    amountOverrides: [],
    createdAt: '2025-04-01T10:00:00.000Z',
    discountAssignments: [],
    effectiveFrom: '2025-04-01',
    enrollmentId: 'enrollment-student-rahul-previous',
    feeStructureId: 'fee-structure-c05-closed',
    id: 'fee-assignment-rahul-historical',
    optionalItemSelections: [],
    schoolId,
    status: 'INACTIVE',
    studentId: 'student-rahul',
    updatedAt: '2026-03-31T10:00:00.000Z',
  },
];
