import type {
  AppNotification,
  CommunicationRecord,
  CommunicationSettings,
  MessageTemplate,
  ReminderRule,
  ScheduledReminder,
} from '../../models/communication';
import { TEMPLATE_VARIABLES } from '../../models/communication';

const schoolId = 'school-omt';
const createdAt = '2026-07-30T08:00:00.000Z';
const all = [...TEMPLATE_VARIABLES] as MessageTemplate['allowedVariables'];

function template(
  id: string,
  code: string,
  name: string,
  communicationType: MessageTemplate['communicationType'],
  content: string,
  requiredVariables: MessageTemplate['requiredVariables'],
): MessageTemplate {
  return {
    allowedVariables: all,
    channel: 'WHATSAPP',
    code,
    communicationType,
    content,
    createdAt,
    id,
    includeReceiptLink: content.includes('{{receiptLink}}'),
    includeSchoolContact: content.includes('{{schoolPhone}}'),
    isDefault: true,
    language: 'ENGLISH',
    name,
    requiredVariables,
    schoolId,
    status: 'ACTIVE',
    updatedAt: createdAt,
  };
}

export const INITIAL_COMMUNICATION_SETTINGS: CommunicationSettings[] = [
  {
    automatedReminderEnabled: true,
    defaultLanguage: 'ENGLISH',
    defaultWhatsAppCountryCode: '+91',
    manualShareEnabled: true,
    maximumRetryCount: 3,
    providerConfigurationStatus: 'DEVELOPMENT_MOCK',
    receiptLinkExpiryLabel: 'Development link · expires in 7 days',
    reminderTime: '09:00',
    reminderTimezone: 'Asia/Kolkata',
    schoolContactNumber: '+919876543200',
    schoolId,
    updatedAt: createdAt,
  },
];

export const INITIAL_MESSAGE_TEMPLATES: MessageTemplate[] = [
  template(
    'template-payment-confirmation',
    'PAYMENT_CONFIRMATION_EN',
    'Payment confirmation',
    'PAYMENT_CONFIRMATION',
    'Dear {{parentName}}, {{paymentAmount}} has been received for {{studentName}} on {{paymentDate}} via {{paymentMode}}. Receipt No: {{receiptNumber}}. Thank you. — {{schoolName}}',
    [
      'parentName',
      'paymentAmount',
      'studentName',
      'paymentDate',
      'paymentMode',
      'receiptNumber',
      'schoolName',
    ],
  ),
  template(
    'template-receipt-share',
    'RECEIPT_SHARE_EN',
    'Receipt share',
    'RECEIPT_SHARE',
    'Dear {{parentName}}, receipt {{receiptNumber}} for {{studentName}} ({{paymentAmount}}) is available here: {{receiptLink}}. — {{schoolName}}',
    [
      'parentName',
      'receiptNumber',
      'studentName',
      'paymentAmount',
      'receiptLink',
      'schoolName',
    ],
  ),
  template(
    'template-upcoming-due',
    'UPCOMING_DUE_EN',
    'Upcoming fee reminder',
    'UPCOMING_DUE_REMINDER',
    'Dear {{parentName}}, a fee of {{outstandingAmount}} for {{studentName}} ({{feePeriod}}) is due on {{dueDate}}. Thank you. — {{schoolName}}',
    [
      'parentName',
      'outstandingAmount',
      'studentName',
      'feePeriod',
      'dueDate',
      'schoolName',
    ],
  ),
  template(
    'template-due-date',
    'DUE_DATE_EN',
    'Due today reminder',
    'DUE_DATE_REMINDER',
    'Dear {{parentName}}, {{studentName}}’s fee is due today. Current outstanding: {{outstandingAmount}}. Thank you. — {{schoolName}}',
    ['parentName', 'studentName', 'outstandingAmount', 'schoolName'],
  ),
  template(
    'template-overdue',
    'OVERDUE_EN',
    'Overdue fee reminder',
    'OVERDUE_REMINDER',
    'Dear {{parentName}}, {{studentName}} has an outstanding fee of {{outstandingAmount}}, including fine {{fineAmount}}, originally due {{dueDate}}. Please contact {{schoolName}} if you need assistance.',
    [
      'parentName',
      'studentName',
      'outstandingAmount',
      'fineAmount',
      'dueDate',
      'schoolName',
    ],
  ),
  template(
    'template-manual-due',
    'MANUAL_DUE_EN',
    'Manual outstanding reminder',
    'MANUAL_DUE_REMINDER',
    'Dear {{parentName}}, the current outstanding for {{studentName}} is {{outstandingAmount}}. Please contact {{schoolName}} if you need any assistance. Thank you.',
    ['parentName', 'studentName', 'outstandingAmount', 'schoolName'],
  ),
  template(
    'template-result-published',
    'RESULT_PUBLISHED_EN',
    'Result published',
    'RESULT_PUBLISHED',
    'Dear {{parentName}}, the {{examName}} result for {{studentName}} ({{className}} {{sectionName}}) has been published. Percentage: {{percentage}}. Grade: {{grade}}. Please sign in to review the result. — {{schoolName}}',
    [
      'parentName',
      'examName',
      'studentName',
      'className',
      'sectionName',
      'percentage',
      'grade',
      'schoolName',
    ],
  ),
  template(
    'template-report-card-available',
    'REPORT_CARD_AVAILABLE_EN',
    'Report card available',
    'REPORT_CARD_AVAILABLE',
    'Dear {{parentName}}, report card {{reportCardNumber}} for {{studentName}} — {{examName}} is now available in the app. — {{schoolName}}',
    ['parentName', 'reportCardNumber', 'studentName', 'examName', 'schoolName'],
  ),
  template(
    'template-report-card-share',
    'REPORT_CARD_SHARE_EN',
    'Report card share',
    'REPORT_CARD_SHARE',
    'Dear {{parentName}}, report card {{reportCardNumber}} for {{studentName}} is available at this development link: {{reportCardLink}}. Please use the app for the latest active version. — {{schoolName}}',
    [
      'parentName',
      'reportCardNumber',
      'studentName',
      'reportCardLink',
      'schoolName',
    ],
  ),
];

export const INITIAL_REMINDER_RULES: ReminderRule[] = [
  {
    branchIds: ['branch-main'],
    code: 'UPCOMING_5_DAYS',
    communicationType: 'UPCOMING_DUE_REMINDER',
    createdAt,
    dayOffset: 5,
    id: 'rule-upcoming-five-days',
    includeFine: false,
    minimumOutstandingPaise: 100,
    name: 'Five days before due',
    schoolId,
    sendTime: '09:00',
    status: 'ACTIVE',
    templateId: 'template-upcoming-due',
    timezone: 'Asia/Kolkata',
    triggerType: 'BEFORE_DUE_DATE',
    updatedAt: createdAt,
  },
  {
    branchIds: ['branch-main'],
    code: 'OVERDUE_WEEKLY',
    communicationType: 'OVERDUE_REMINDER',
    createdAt,
    dayOffset: 7,
    id: 'rule-overdue-weekly',
    includeFine: true,
    maximumOccurrences: 4,
    minimumOutstandingPaise: 10_000,
    name: 'Weekly overdue reminder',
    repeatEveryDays: 7,
    schoolId,
    sendTime: '09:00',
    status: 'ACTIVE',
    templateId: 'template-overdue',
    timezone: 'Asia/Kolkata',
    triggerType: 'RECURRING_OVERDUE',
    updatedAt: createdAt,
  },
  {
    branchIds: ['branch-main'],
    code: 'PAUSED_DUE_DAY',
    communicationType: 'DUE_DATE_REMINDER',
    createdAt,
    dayOffset: 0,
    id: 'rule-paused-due-day',
    includeFine: false,
    name: 'Paused due-date reminder',
    schoolId,
    sendTime: '09:00',
    status: 'PAUSED',
    templateId: 'template-due-date',
    timezone: 'Asia/Kolkata',
    triggerType: 'ON_DUE_DATE',
    updatedAt: createdAt,
  },
];

const snapshot = {
  channel: 'WHATSAPP' as const,
  code: 'OVERDUE_EN',
  content: INITIAL_MESSAGE_TEMPLATES[4].content,
  language: 'ENGLISH' as const,
  name: 'Overdue fee reminder',
  variablesUsed: { studentName: 'Rahul Patel' },
};
export const INITIAL_COMMUNICATION_RECORDS: CommunicationRecord[] = [
  {
    attemptNumber: 1,
    branchId: 'branch-main',
    channel: 'WHATSAPP',
    communicationType: 'OVERDUE_REMINDER',
    createdAt: '2026-07-30T09:00:00.000Z',
    failedAt: '2026-07-30T09:00:01.000Z',
    failureCode: 'DEVELOPMENT_MOCK_FAILURE',
    failureReason: 'Simulated provider failure. No message was sent.',
    feeDueIds: ['due-rahul-june-daily'],
    guardianId: 'guardian-student-rahul',
    id: 'communication-failed-overdue',
    idempotencyKey: 'fixture::overdue::attempt::1',
    logicalIdempotencyKey: 'fixture::overdue',
    mode: 'PROVIDER_SEND',
    parentMembershipId: 'membership-parent',
    recipientMobileMasked: '+91 ••••••3212',
    recipientName: 'Meera Patel',
    renderedContent: 'Development mock overdue reminder for Rahul Patel.',
    schoolId,
    status: 'FAILED',
    studentId: 'student-rahul',
    templateId: 'template-overdue',
    templateSnapshot: snapshot,
    updatedAt: '2026-07-30T09:00:01.000Z',
  },
  {
    attemptNumber: 1,
    branchId: 'branch-main',
    channel: 'WHATSAPP',
    communicationType: 'RECEIPT_SHARE',
    createdAt: '2026-07-30T10:00:00.000Z',
    feeDueIds: [],
    guardianId: 'guardian-student-rahul',
    id: 'communication-receipt-handoff',
    idempotencyKey: 'fixture::receipt::handoff',
    logicalIdempotencyKey: 'fixture::receipt::handoff',
    mode: 'MANUAL_SHARE',
    parentMembershipId: 'membership-parent',
    receiptId: 'receipt-advance-rahul',
    recipientMobileMasked: '+91 ••••••3212',
    recipientName: 'Meera Patel',
    renderedContent: 'Receipt shared through the device share sheet.',
    schoolId,
    status: 'HANDED_OFF',
    studentId: 'student-rahul',
    templateId: 'template-receipt-share',
    templateSnapshot: {
      ...snapshot,
      code: 'RECEIPT_SHARE_EN',
      name: 'Receipt share',
    },
    updatedAt: '2026-07-30T10:00:00.000Z',
  },
  ...(['SENT', 'DELIVERED', 'READ'] as const).map(
    (status, index): CommunicationRecord => ({
      attemptNumber: 1,
      branchId: 'branch-main',
      channel: 'WHATSAPP',
      communicationType: 'UPCOMING_DUE_REMINDER',
      createdAt: `2026-07-29T0${index + 7}:00:00.000Z`,
      deliveredAt:
        status !== 'SENT' ? `2026-07-29T0${index + 7}:01:00.000Z` : undefined,
      feeDueIds: ['due-rahul-august'],
      guardianId: 'guardian-student-rahul',
      id: `communication-provider-${status.toLowerCase()}`,
      idempotencyKey: `fixture::provider::${status.toLowerCase()}::1`,
      logicalIdempotencyKey: `fixture::provider::${status.toLowerCase()}`,
      mode: 'PROVIDER_SEND',
      parentMembershipId: 'membership-parent',
      providerMessageId: `development-mock-${index + 1}`,
      providerStatus: `DEVELOPMENT_MOCK_${status}`,
      readAt: status === 'READ' ? '2026-07-29T09:02:00.000Z' : undefined,
      recipientMobileMasked: '+91 ••••••3212',
      recipientName: 'Meera Patel',
      renderedContent:
        'Development mock upcoming fee reminder for Rahul Patel.',
      schoolId,
      sentAt: `2026-07-29T0${index + 7}:00:00.000Z`,
      status,
      studentId: 'student-rahul',
      templateId: 'template-upcoming-due',
      templateSnapshot: {
        ...snapshot,
        code: 'UPCOMING_DUE_EN',
        name: 'Upcoming fee reminder',
      },
      updatedAt: `2026-07-29T0${index + 7}:02:00.000Z`,
    }),
  ),
];

export const INITIAL_SCHEDULED_REMINDERS: ScheduledReminder[] = [
  {
    branchId: 'branch-main',
    createdAt,
    feeDueId: 'due-rahul-august',
    guardianId: 'guardian-student-rahul',
    id: 'scheduled-upcoming-rahul',
    idempotencyKey: 'rule-upcoming-five-days::due-rahul-august::2026-08-05::1',
    occurrenceNumber: 1,
    parentMembershipId: 'membership-parent',
    recipientMobileMasked: '+91 ••••••3212',
    reminderRuleId: 'rule-upcoming-five-days',
    scheduledFor: '2026-08-05T09:00:00+05:30',
    schoolId,
    status: 'SCHEDULED',
    studentId: 'student-rahul',
    templateId: 'template-upcoming-due',
    updatedAt: createdAt,
  },
  {
    branchId: 'branch-main',
    createdAt,
    failureReason: 'Cancelled after the School calendar changed.',
    feeDueId: 'due-rahul-august',
    guardianId: 'guardian-student-rahul',
    id: 'scheduled-cancelled-rahul',
    idempotencyKey: 'rule-paused-due-day::due-rahul-august::2026-08-10::1',
    occurrenceNumber: 1,
    parentMembershipId: 'membership-parent',
    recipientMobileMasked: '+91 ••••••3212',
    reminderRuleId: 'rule-paused-due-day',
    scheduledFor: '2026-08-10T09:00:00+05:30',
    schoolId,
    status: 'CANCELLED',
    studentId: 'student-rahul',
    templateId: 'template-due-date',
    updatedAt: createdAt,
  },
];

function notification(
  id: string,
  audienceType: AppNotification['audienceType'],
  audienceId: string,
  title: string,
  studentId?: string,
  type: AppNotification['type'] = 'GENERAL_FEE_NOTICE',
): AppNotification {
  return {
    audienceId,
    audienceType,
    branchId: 'branch-main',
    createdAt,
    id,
    message: `${title}${studentId ? ' for the linked student.' : '.'}`,
    schoolId,
    status: 'UNREAD',
    studentId,
    title,
    type,
  };
}
export const INITIAL_APP_NOTIFICATIONS: AppNotification[] = [
  notification(
    'notification-staff-payment',
    'STAFF_USER',
    'membership-school-admin',
    'Payment received',
    'student-rahul',
    'PAYMENT_CONFIRMATION',
  ),
  notification(
    'notification-parent-receipt',
    'PARENT_MEMBERSHIP',
    'membership-parent',
    'Receipt available',
    'student-rahul',
    'RECEIPT_SHARE',
  ),
  notification(
    'notification-parent-overdue',
    'PARENT_MEMBERSHIP',
    'membership-parent',
    'Fee became overdue',
    'student-isha',
    'OVERDUE_REMINDER',
  ),
  notification(
    'notification-student-due',
    'STUDENT_MEMBERSHIP',
    'membership-student',
    'Fee due generated',
    'student-rahul',
    'UPCOMING_DUE_REMINDER',
  ),
  notification(
    'notification-staff-fine',
    'STAFF_USER',
    'membership-school-admin',
    'Fine updated',
    'student-rahul',
    'FINE_UPDATED_NOTICE',
  ),
  notification(
    'notification-staff-reminder-sent',
    'STAFF_USER',
    'membership-school-admin',
    'Reminder sent',
    'student-rahul',
    'MANUAL_DUE_REMINDER',
  ),
  notification(
    'notification-staff-reminder-failed',
    'STAFF_USER',
    'membership-school-admin',
    'Reminder failed',
    'student-rahul',
    'OVERDUE_REMINDER',
  ),
];

export const COMMUNICATION_RECIPIENT_SCENARIOS = {
  invalidMobile:
    'A resolver-level scenario; malformed numbers are rejected before send.',
  missingMobile:
    'A resolver-level scenario; missing guardians are surfaced in bulk preview.',
  multiChildParent: ['student-rahul', 'student-isha'],
  whatsappDisabled:
    'Automated resolution rejects an active link when opt-in is disabled.',
} as const;
