import type { AppRole } from '../../constants/permissions';
import {
  PERMISSION_KEYS,
  type PermissionKey,
} from '../../constants/userPermissions';
import type { RoleDefinition } from '../../models/userManagement';

const USER_MANAGEMENT = PERMISSION_KEYS.filter(key => key.startsWith('users.'));
const EXAM_MANAGEMENT = PERMISSION_KEYS.filter(
  key =>
    key.startsWith('exams.') ||
    key.startsWith('marks.') ||
    key.startsWith('results.') ||
    key.startsWith('report_cards.') ||
    key.startsWith('exam_reports.'),
);

const definitions: Record<
  AppRole,
  Omit<RoleDefinition, 'activeMembershipCount'>
> = {
  SUPER_ADMIN: {
    configurablePermissions: [],
    defaultPermissions: [...PERMISSION_KEYS],
    description: 'Platform-wide administration across every school.',
    isSystemRole: true,
    label: 'Super Admin',
    prohibitedPermissions: [],
    role: 'SUPER_ADMIN',
    scope: 'PLATFORM',
  },
  SCHOOL_ADMIN: {
    configurablePermissions: [],
    defaultPermissions: [...PERMISSION_KEYS],
    description: 'Full administration of one school and all its branches.',
    isSystemRole: true,
    label: 'School Admin',
    prohibitedPermissions: [],
    role: 'SCHOOL_ADMIN',
    scope: 'SCHOOL',
  },
  BRANCH_ADMIN: {
    configurablePermissions: [
      'academic.class.manage',
      'academic.section.manage',
      'students.status.manage',
      'students.transfer',
      'students.access.manage',
      'fees.student_assignment.manage',
      'fees.discount.manage',
      'fees.fine.manage',
      'fees.override.manage',
      'fees.exemption.manage',
      'fees.due.generate',
      'fees.due.cancel',
      'fees.due.waive',
      'fees.fine.refresh',
      'fees.fine.waive',
      'payments.reverse',
      'payments.advance.manage',
      'receipts.cancel',
      'marks.unlock',
      'marks.exempt',
      'results.publish',
      'results.unpublish',
      'results.publication_history.view',
      'report_cards.revoke',
      'fee_reports.export',
      'exam_reports.export',
      'reports.audit.view',
      'communication.send.bulk',
      'communication.reminders.manage',
      'communication.failed.retry',
      'exams.cancel',
    ],
    defaultPermissions: [
      'organization.school.view',
      'organization.branch.view',
      'organization.session.view',
      'users.view',
      'academic.class.view',
      'academic.section.view',
      'academic.subject.view',
      'students.view',
      'students.create',
      'students.edit',
      'students.guardians.manage',
      'students.enrollment.manage',
      'students.history.view',
      'fees.view',
      'fees.structure.manage',
      'fees.generate',
      'fees.due.view',
      'fees.generation_history.view',
      'payments.collect',
      'payments.view',
      'payments.advance.view',
      'collection.daily.view',
      'receipts.view',
      'receipts.share',
      'ledger.view',
      'fee_reports.view',
      'reports.dashboard.view',
      'reports.students.view',
      'reports.collections.view',
      'reports.communication.view',
      'reports.saved_filters.manage',
      'reports.export_history.view',
      'communication.templates.view',
      'communication.reminders.view',
      'communication.send.manual',
      'communication.history.view',
      'notifications.view',
      'exams.view',
      'exams.manage',
      'exams.schedule.manage',
      'marks.view',
      'marks.enter',
      'marks.submit',
      'marks.lock',
      'marks.history.view',
      'results.view',
      'results.calculate',
      'results.review',
      'results.rank.view',
      'report_cards.view',
      'report_cards.generate',
      'report_cards.history.view',
      'report_cards.share',
      'results.communication.send',
      'exam_reports.view',
    ],
    description: 'Administration within assigned active branches.',
    isSystemRole: true,
    label: 'Branch Admin',
    prohibitedPermissions: [
      'organization.school.edit',
      'organization.branch.create',
      'organization.settings.edit',
      'users.create',
      'users.edit',
      'users.role.assign',
    ],
    role: 'BRANCH_ADMIN',
    scope: 'BRANCH',
  },
  ACCOUNTANT: {
    configurablePermissions: [
      'receipts.share',
      'fee_reports.export',
      'reports.saved_filters.manage',
      'fees.discount.manage',
      'fees.fine.manage',
      'fees.due.generate',
      'payments.advance.manage',
    ],
    defaultPermissions: [
      'organization.school.view',
      'organization.branch.view',
      'organization.session.view',
      'students.view',
      'fees.view',
      'fees.due.view',
      'fees.generation_history.view',
      'fees.fine.refresh',
      'payments.collect',
      'payments.view',
      'payments.advance.view',
      'collection.daily.view',
      'receipts.view',
      'ledger.view',
      'fee_reports.view',
      'fee_reports.export',
      'reports.dashboard.view',
      'reports.collections.view',
      'reports.export_history.view',
      'communication.send.manual',
      'communication.history.view',
      'notifications.view',
    ],
    description: 'Branch-scoped fee collection, receipts, ledger, and reports.',
    isSystemRole: true,
    label: 'Accountant',
    prohibitedPermissions: [
      ...EXAM_MANAGEMENT,
      ...USER_MANAGEMENT,
      'organization.settings.view',
      'organization.settings.edit',
      'payments.reverse',
      'communication.templates.view',
      'communication.templates.manage',
      'communication.settings.view',
      'communication.settings.manage',
      'communication.reminders.view',
      'communication.reminders.manage',
    ],
    role: 'ACCOUNTANT',
    scope: 'BRANCH',
  },
  RECEPTIONIST: {
    configurablePermissions: [
      'payments.collect',
      'receipts.view',
      'communication.send.manual',
      'notifications.view',
      'reports.dashboard.view',
      'reports.students.view',
      'fee_reports.view',
    ],
    defaultPermissions: [
      'organization.school.view',
      'organization.branch.view',
      'organization.session.view',
      'students.view',
      'students.create',
      'students.edit',
      'students.guardians.manage',
      'students.history.view',
      'fees.view',
      'fees.due.view',
      'payments.view',
    ],
    description: 'Branch front-desk access for admissions and student details.',
    isSystemRole: true,
    label: 'Receptionist',
    prohibitedPermissions: [
      ...USER_MANAGEMENT,
      ...EXAM_MANAGEMENT,
      'fees.structure.manage',
      'payments.reverse',
      'payments.advance.view',
      'payments.advance.manage',
      'collection.daily.view',
      'receipts.cancel',
      'organization.settings.view',
      'organization.settings.edit',
      'communication.templates.view',
      'communication.templates.manage',
      'communication.settings.view',
      'communication.settings.manage',
      'communication.reminders.view',
      'communication.reminders.manage',
      'communication.send.bulk',
      'communication.history.view',
      'communication.failed.retry',
      'fee_reports.export',
      'reports.collections.view',
      'reports.communication.view',
      'reports.audit.view',
      'reports.saved_filters.manage',
      'reports.export_history.view',
    ],
    role: 'RECEPTIONIST',
    scope: 'BRANCH',
  },
  PARENT: {
    configurablePermissions: [],
    defaultPermissions: [
      'students.view',
      'fees.view',
      'fees.due.view',
      'payments.view',
      'receipts.view',
      'results.view',
      'report_cards.view',
      'results.self_service.view',
      'notifications.view',
    ],
    description: 'Read-only self-service access linked through a student.',
    isSystemRole: true,
    label: 'Parent',
    prohibitedPermissions: [...USER_MANAGEMENT],
    role: 'PARENT',
    scope: 'SELF',
  },
  STUDENT: {
    configurablePermissions: [],
    defaultPermissions: [
      'students.view',
      'fees.view',
      'fees.due.view',
      'payments.view',
      'receipts.view',
      'results.view',
      'report_cards.view',
      'results.self_service.view',
      'notifications.view',
    ],
    description: 'Read-only self-service student access.',
    isSystemRole: true,
    label: 'Student',
    prohibitedPermissions: [...USER_MANAGEMENT],
    role: 'STUDENT',
    scope: 'SELF',
  },
};

export const SYSTEM_ROLE_DEFINITIONS = definitions;

export function getBaseRoleDefinition(
  role: AppRole,
): Omit<RoleDefinition, 'activeMembershipCount'> {
  return definitions[role];
}

export function isPermissionConfigurable(
  role: AppRole,
  permission: PermissionKey,
): boolean {
  return definitions[role].configurablePermissions.includes(permission);
}
