import type {
  SchoolRoleConfiguration,
  StaffMembership,
  UserActivity,
  UserIdentity,
  UserSessionSummary,
} from '../../models/userManagement';
import type { AppRole } from '../../constants/permissions';

const now = '2026-07-20T10:00:00.000Z';
const createdAt = '2025-04-01T09:00:00.000Z';

export const INITIAL_USER_IDENTITIES: UserIdentity[] = [
  {
    createdAt,
    email: 'ananya@omt.edu.in',
    id: 'user-school-admin',
    lastLoginAt: '2026-07-20T08:30:00.000Z',
    mobile: '9876543210',
    name: 'Ananya Sharma',
    status: 'ACTIVE',
    updatedAt: now,
  },
  {
    createdAt,
    email: 'rohit@omt.edu.in',
    id: 'user-branch-admin',
    lastLoginAt: '2026-07-19T11:20:00.000Z',
    mobile: '9876543215',
    name: 'Rohit Das',
    status: 'ACTIVE',
    updatedAt: now,
  },
  {
    createdAt,
    email: 'vikram@omt.edu.in',
    id: 'user-accountant',
    lastLoginAt: '2026-07-20T07:45:00.000Z',
    mobile: '9876543211',
    name: 'Vikram Rao',
    status: 'ACTIVE',
    updatedAt: now,
  },
  {
    createdAt,
    email: 'neha@omt.edu.in',
    id: 'user-receptionist',
    lastLoginAt: '2026-07-18T09:10:00.000Z',
    mobile: '9876543216',
    name: 'Neha Singh',
    status: 'ACTIVE',
    updatedAt: now,
  },
  {
    createdAt,
    id: 'user-inactive-staff',
    mobile: '9860000010',
    name: 'Inactive Staff',
    status: 'ACTIVE',
    updatedAt: now,
  },
  {
    createdAt,
    email: 'amit@example.in',
    id: 'user-existing-amit',
    mobile: '9860000099',
    name: 'Amit Kumar',
    status: 'ACTIVE',
    updatedAt: now,
  },
  {
    createdAt,
    id: 'user-global-inactive',
    mobile: '9860000088',
    name: 'Disabled Identity',
    status: 'INACTIVE',
    updatedAt: now,
  },
  {
    createdAt,
    id: 'user-greenfield-admin',
    mobile: '9860000077',
    name: 'Greenfield Branch Lead',
    status: 'ACTIVE',
    updatedAt: now,
  },
];

export const INITIAL_STAFF_MEMBERSHIPS: StaffMembership[] = [
  {
    branchIds: [],
    createdAt,
    id: 'membership-school-admin',
    role: 'SCHOOL_ADMIN',
    schoolId: 'school-omt',
    status: 'ACTIVE',
    updatedAt: now,
    userId: 'user-school-admin',
  },
  {
    branchIds: ['branch-main'],
    createdAt,
    id: 'membership-branch-admin',
    role: 'BRANCH_ADMIN',
    schoolId: 'school-omt',
    status: 'ACTIVE',
    updatedAt: now,
    userId: 'user-branch-admin',
  },
  {
    branchIds: ['branch-main'],
    createdAt,
    id: 'membership-accountant',
    role: 'ACCOUNTANT',
    schoolId: 'school-omt',
    status: 'ACTIVE',
    updatedAt: now,
    userId: 'user-accountant',
  },
  {
    branchIds: ['branch-main'],
    createdAt,
    id: 'membership-reception',
    role: 'RECEPTIONIST',
    schoolId: 'school-omt',
    status: 'ACTIVE',
    updatedAt: now,
    userId: 'user-receptionist',
  },
  {
    branchIds: ['branch-main'],
    createdAt,
    id: 'membership-inactive-staff',
    role: 'RECEPTIONIST',
    schoolId: 'school-omt',
    status: 'INACTIVE',
    updatedAt: now,
    userId: 'user-inactive-staff',
  },
  {
    branchIds: ['branch-school-sunrise-main'],
    createdAt,
    id: 'membership-existing-amit-sunrise',
    role: 'ACCOUNTANT',
    schoolId: 'school-sunrise',
    status: 'ACTIVE',
    updatedAt: now,
    userId: 'user-existing-amit',
  },
  {
    branchIds: [
      'branch-school-greenfield-main',
      'branch-greenfield-puri',
    ],
    createdAt,
    id: 'membership-greenfield-branches',
    role: 'BRANCH_ADMIN',
    schoolId: 'school-greenfield',
    status: 'ACTIVE',
    updatedAt: now,
    userId: 'user-greenfield-admin',
  },
];

export const INITIAL_ROLE_CONFIGURATIONS: SchoolRoleConfiguration[] = (
  ['BRANCH_ADMIN', 'ACCOUNTANT', 'RECEPTIONIST'] as AppRole[]
).map(role => ({
  disabledPermissions: [],
  enabledPermissions: [],
  role,
  schoolId: 'school-omt',
  updatedAt: now,
}));

export const INITIAL_USER_SESSIONS: UserSessionSummary[] = [
  {
    approximateDeviceId: '…A72F',
    deviceLabel: 'Samsung Galaxy S24',
    id: 'session-accountant-current',
    isCurrent: true,
    lastActiveAt: '2026-07-20T09:55:00.000Z',
    loggedInAt: '2026-07-20T07:45:00.000Z',
    membershipId: 'membership-accountant',
    platform: 'ANDROID',
    status: 'ACTIVE',
  },
  {
    approximateDeviceId: '…9BC1',
    deviceLabel: 'Chrome on Windows',
    id: 'session-accountant-web',
    isCurrent: false,
    lastActiveAt: '2026-07-19T17:30:00.000Z',
    loggedInAt: '2026-07-18T08:00:00.000Z',
    membershipId: 'membership-accountant',
    platform: 'WEB',
    status: 'ACTIVE',
  },
  {
    approximateDeviceId: '…D118',
    deviceLabel: 'OnePlus 12',
    id: 'session-branch-admin-current',
    isCurrent: true,
    lastActiveAt: '2026-07-19T11:20:00.000Z',
    loggedInAt: '2026-07-19T08:10:00.000Z',
    membershipId: 'membership-branch-admin',
    platform: 'ANDROID',
    status: 'ACTIVE',
  },
];

export const INITIAL_USER_ACTIVITY: UserActivity[] = [
  {
    action: 'MEMBERSHIP_CREATED',
    description: 'Accountant membership created for Main Branch.',
    id: 'activity-1',
    performedAt: createdAt,
    performedByName: 'Ananya Sharma',
    performedByUserId: 'user-school-admin',
    schoolId: 'school-omt',
    targetMembershipId: 'membership-accountant',
    targetUserId: 'user-accountant',
  },
  {
    action: 'LOGIN_INSTRUCTIONS_SENT',
    description: 'OTP login instructions sent to mobile ending 3211.',
    id: 'activity-2',
    performedAt: '2026-07-18T10:00:00.000Z',
    performedByName: 'Ananya Sharma',
    performedByUserId: 'user-school-admin',
    schoolId: 'school-omt',
    targetMembershipId: 'membership-accountant',
    targetUserId: 'user-accountant',
  },
];
