import React, { useEffect, useState } from 'react';
import { StyleSheet, View } from 'react-native';

import { AppBadge } from '../../components/common/AppBadge';
import { AppButton } from '../../components/common/AppButton';
import { AppCard } from '../../components/common/AppCard';
import { AppHeader } from '../../components/common/AppHeader';
import { AppInput } from '../../components/common/AppInput';
import { AppScreen } from '../../components/common/AppScreen';
import { AppText } from '../../components/common/AppText';
import { EmptyState } from '../../components/feedback/EmptyState';
import { ErrorState } from '../../components/feedback/ErrorState';
import { LoadingView } from '../../components/feedback/LoadingView';
import { ROUTES } from '../../constants/routes';
import type {
  ReportCard,
  ReportCardTemplate,
  SelfServiceResultDetails,
} from '../../models/reportCard';
import type { RoleScreenProps } from '../../navigation/navigationTypes';
import { useReportCardStore } from '../../store';

type StaffParams = RoleScreenProps<'ReportCardDashboard'>['route']['params'];
type BackNavigation = { goBack(): void };

function useStaffContext(params: StaffParams) {
  const setContext = useReportCardStore(state => state.setContext);
  useEffect(
    () =>
      setContext({
        academicSessionId: params.academicSessionId,
        branchId: params.branchId,
        examId: params.examId,
        schoolId: params.schoolId,
        sessionStatus: params.sessionStatus,
      }),
    [
      params.academicSessionId,
      params.branchId,
      params.examId,
      params.schoolId,
      params.sessionStatus,
      setContext,
    ],
  );
}

function useWorkspace(schoolId: string) {
  const setContext = useReportCardStore(state => state.setContext);
  useEffect(
    () =>
      setContext({
        academicSessionId: '',
        branchId: '',
        examId: '',
        schoolId,
        sessionStatus: 'ACTIVE',
      }),
    [schoolId, setContext],
  );
}

function Shell({
  children,
  navigation,
  title,
  testID,
  subtitle,
}: {
  children: React.ReactNode;
  navigation: BackNavigation;
  title: string;
  testID: string;
  subtitle?: string;
}) {
  return (
    <AppScreen scrollable testID={testID}>
      <View style={styles.content}>
        <AppHeader
          includeSafeArea={false}
          onBackPress={navigation.goBack}
          subtitle={subtitle}
          title={title}
        />
        <Feedback />
        {children}
      </View>
    </AppScreen>
  );
}

function Feedback() {
  const error = useReportCardStore(state => state.error);
  const success = useReportCardStore(state => state.successMessage);
  return (
    <>
      {error ? <ErrorState message={error.message} /> : null}
      {success ? <AppText style={styles.feedback}>{success}</AppText> : null}
    </>
  );
}

const value = (label: string, text: string | number | undefined) => (
  <View style={styles.row}>
    <AppText variant="caption">{label}</AppText>
    <AppText style={styles.rowValue}>{text ?? '—'}</AppText>
  </View>
);

function Status({ status }: { status: string }) {
  const positive = [
    'ACTIVE',
    'AVAILABLE',
    'COMPLETED',
    'DOCUMENT_READY',
    'PUBLISHED',
  ].includes(status);
  const negative = [
    'FAILED',
    'REVOKED',
    'INACTIVE',
    'DOCUMENT_FAILED',
  ].includes(status);
  return (
    <AppBadge
      label={status.replaceAll('_', ' ')}
      status={positive ? 'active' : negative ? 'failed' : 'draft'}
    />
  );
}

function TemplateCard({
  item,
  onPress,
}: {
  item: ReportCardTemplate;
  onPress?: () => void;
}) {
  return (
    <AppCard onPress={onPress} style={styles.card} variant="outlined">
      <View style={styles.between}>
        <AppText variant="title">{item.name}</AppText>
        <Status status={item.status} />
      </View>
      <AppText>
        {item.title} · {item.layoutType}
      </AppText>
      <AppText variant="caption">
        {item.code}
        {item.isDefault ? ' · Default' : ''}
      </AppText>
    </AppCard>
  );
}

function ReportCardView({
  card,
  safe = false,
}: {
  card: ReportCard;
  safe?: boolean;
}) {
  return (
    <>
      <AppCard style={styles.card} variant="outlined">
        <View style={styles.between}>
          <AppText variant="title">{card.reportCardNumber}</AppText>
          <Status status={card.status} />
        </View>
        {value('Version', card.version)}
        {value('Document', card.documentStatus)}
        {value('Generated', card.generatedAt.slice(0, 10))}
        {!safe ? value('Publication batch', card.publicationBatchId) : null}
        {!safe ? value('Generated by', card.generatedByName) : null}
      </AppCard>
      <AppCard
        header={<AppText variant="title">Student</AppText>}
        style={styles.card}
        variant="outlined"
      >
        {value('Name', card.studentSnapshot.name)}
        {value('Admission number', card.studentSnapshot.admissionNumber)}
        {value('Roll number', card.studentSnapshot.rollNumber)}
        {value('Class', card.studentSnapshot.className)}
        {value('Section', card.studentSnapshot.sectionName)}
      </AppCard>
      <AppCard
        header={<AppText variant="title">Academic result</AppText>}
        style={styles.card}
        variant="outlined"
      >
        {value('Exam', card.examSnapshot.name)}
        {value('Term', card.examSnapshot.termName)}
        {value('Exam type', card.examSnapshot.examTypeName)}
        {value('Percentage', `${card.overallResult.percentage.toFixed(2)}%`)}
        {value('Grade', card.overallResult.grade)}
        {value('Outcome', card.overallResult.outcome)}
        {value('Rank', card.overallResult.rank)}
        {card.subjectResults.map(subject => (
          <View key={subject.id} style={styles.subject}>
            <AppText variant="bodyMedium">
              {subject.subjectNameSnapshot}
            </AppText>
            <AppText>
              {subject.marksObtained}/{subject.maximumMarks} ·{' '}
              {subject.grade ?? subject.outcome}
            </AppText>
            {subject.componentResults.map(component => (
              <AppText key={component.assessmentComponentId} variant="caption">
                {component.componentNameSnapshot}:{' '}
                {component.marksObtained ?? '—'}/
                {component.maximumMarksSnapshot}
              </AppText>
            ))}
          </View>
        ))}
      </AppCard>
      <AppCard
        header={<AppText variant="title">Template snapshot</AppText>}
        style={styles.card}
        variant="outlined"
      >
        {value('Name', card.templateSnapshot.name)}
        {value('Code', card.templateSnapshot.code)}
        {value('Updated', card.templateSnapshot.templateUpdatedAt.slice(0, 10))}
      </AppCard>
    </>
  );
}

function ResultView({ result }: { result: SelfServiceResultDetails }) {
  return (
    <>
      <AppCard style={styles.card} variant="outlined">
        <AppText variant="title">{result.summary.examName}</AppText>
        {value('Student', result.summary.studentName)}
        {value(
          'Class',
          `${result.summary.className} ${result.summary.sectionName}`,
        )}
        {value('Percentage', `${result.summary.percentage.toFixed(2)}%`)}
        {value('Grade', result.summary.grade)}
        {value('Outcome', result.summary.outcome)}
        {value('Rank', result.summary.rank)}
        {value('Published', result.summary.publishedAt.slice(0, 10))}
      </AppCard>
      {result.subjectResults.map(subject => (
        <AppCard key={subject.id} style={styles.card} variant="outlined">
          <AppText variant="title">{subject.subjectNameSnapshot}</AppText>
          {value('Marks', `${subject.marksObtained}/${subject.maximumMarks}`)}
          {value('Grade', subject.grade)}
          {value('Outcome', subject.outcome)}
        </AppCard>
      ))}
    </>
  );
}

export function ReportCardDashboardScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardDashboard'>) {
  useStaffContext(route.params);
  const load = useReportCardStore(s => s.loadDashboard);
  const summary = useReportCardStore(s => s.dashboard);
  const loading = useReportCardStore(s => s.isLoadingDashboard);
  useEffect(() => {
    load().catch(() => undefined);
  }, [load, route.params.examId]);
  return (
    <Shell
      navigation={navigation}
      subtitle={`${route.params.branchId} · ${route.params.examId}`}
      testID="report-card-dashboard-screen"
      title="Report Card Dashboard"
    >
      {loading ? (
        <LoadingView />
      ) : summary ? (
        <>
          <View style={styles.grid}>
            {[
              ['Published Students', summary.publishedStudents],
              ['Report Cards Generated', summary.reportCardsGenerated],
              ['Report Cards Available', summary.reportCardsAvailable],
              ['Missing Report Cards', summary.missingReportCards],
              ['Failed Generations', summary.failedGenerations],
              ['Revoked Report Cards', summary.revokedReportCards],
              ['Parent Notifications', summary.parentNotifications],
              ['Student Notifications', summary.studentNotifications],
            ].map(([label, count]) => (
              <AppCard
                key={String(label)}
                style={styles.metric}
                variant="outlined"
              >
                <AppText variant="heading2">{count}</AppText>
                <AppText variant="caption">{label}</AppText>
              </AppCard>
            ))}
          </View>
          {summary.warnings.map(item => (
            <AppText key={item.code} style={styles.warning}>
              ⚠ {item.message}
            </AppText>
          ))}
        </>
      ) : (
        <EmptyState title="No Report Card summary" />
      )}
      <AppButton
        fullWidth
        onPress={() =>
          navigation.navigate(ROUTES.GENERATE_REPORT_CARDS, route.params)
        }
        title="Generate Report Cards"
      />
      <AppButton
        fullWidth
        onPress={() =>
          navigation.navigate(ROUTES.REPORT_CARD_TEMPLATES, {
            schoolId: route.params.schoolId,
          })
        }
        title="Manage Templates"
        variant="outline"
      />
      <AppButton
        fullWidth
        onPress={() => navigation.navigate(ROUTES.REPORT_CARDS, route.params)}
        title="View Report Cards"
        variant="outline"
      />
      <AppButton
        fullWidth
        onPress={() =>
          navigation.navigate(
            ROUTES.REPORT_CARD_GENERATION_HISTORY,
            route.params,
          )
        }
        title="Generation History"
        variant="outline"
      />
      <AppButton
        fullWidth
        onPress={() =>
          navigation.navigate(ROUTES.RESULT_COMMUNICATION, route.params)
        }
        title="Send Result Communication"
        variant="outline"
      />
    </Shell>
  );
}

export function ReportCardTemplatesScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardTemplates'>) {
  useWorkspace(route.params.schoolId);
  const load = useReportCardStore(s => s.loadTemplates);
  const templates = useReportCardStore(s => s.templates);
  const loading = useReportCardStore(s => s.isLoadingTemplates);
  useEffect(() => {
    load().catch(() => undefined);
  }, [load]);
  return (
    <Shell
      navigation={navigation}
      testID="report-card-templates-screen"
      title="Report Card Templates"
    >
      <AppButton
        onPress={() =>
          navigation.navigate(ROUTES.CREATE_REPORT_CARD_TEMPLATE, route.params)
        }
        title="Create Template"
      />
      {loading ? (
        <LoadingView />
      ) : templates.items.length ? (
        templates.items.map(item => (
          <TemplateCard
            item={item}
            key={item.id}
            onPress={() =>
              navigation.navigate(ROUTES.REPORT_CARD_TEMPLATE_DETAILS, {
                schoolId: route.params.schoolId,
                templateId: item.id,
              })
            }
          />
        ))
      ) : (
        <EmptyState title="No Templates" />
      )}
    </Shell>
  );
}

const templateDefaults = {
  code: '',
  name: '',
  title: '',
  layoutType: 'STANDARD' as const,
  description: '',
  subtitle: '',
  footerText: '',
  isDefault: false,
  status: 'DRAFT' as const,
  showSchoolLogo: true,
  showBranchAddress: true,
  showStudentPhoto: false,
  showComponentMarks: true,
  showSubjectPercentage: true,
  showSubjectGrade: true,
  showSubjectOutcome: true,
  showOverallPercentage: true,
  showOverallGrade: true,
  showOverallOutcome: true,
  showRank: true,
  showGradeLegend: true,
  showGenerationMetadata: true,
  principalSignatureLabel: 'Principal',
  schoolAuthoritySignatureLabel: 'School Authority',
  parentSignatureLabel: 'Parent / Guardian',
};

function TemplateForm({
  id,
  navigation,
  schoolId,
}: {
  id?: string;
  navigation: BackNavigation;
  schoolId: string;
}) {
  useWorkspace(schoolId);
  const draft = useReportCardStore(s => s.templateDraft);
  const setDraft = useReportCardStore(s => s.setTemplateDraft);
  const load = useReportCardStore(s => s.loadTemplate);
  const save = useReportCardStore(s => s.saveTemplate);
  const preview = useReportCardStore(s => s.previewTemplate);
  const saving = useReportCardStore(s => s.isSavingTemplate);
  useEffect(() => {
    if (id) load(id).catch(() => undefined);
    else setDraft(templateDefaults);
  }, [id, load, setDraft]);
  return (
    <>
      <AppInput
        label="Name"
        onChangeText={name => setDraft({ name })}
        required
        value={draft.name ?? ''}
      />
      <AppInput
        autoCapitalize="characters"
        label="Code"
        onChangeText={code => setDraft({ code })}
        required
        value={draft.code ?? ''}
      />
      <AppInput
        label="Title"
        onChangeText={title => setDraft({ title })}
        required
        value={draft.title ?? ''}
      />
      <AppInput
        label="Subtitle"
        onChangeText={subtitle => setDraft({ subtitle })}
        value={draft.subtitle ?? ''}
      />
      <AppInput
        label="Footer"
        multiline
        onChangeText={footerText => setDraft({ footerText })}
        value={draft.footerText ?? ''}
      />
      <AppButton
        onPress={() =>
          setDraft({
            layoutType:
              draft.layoutType === 'STANDARD' ? 'COMPACT' : 'STANDARD',
          })
        }
        title={`Layout: ${draft.layoutType ?? 'STANDARD'}`}
        variant="outline"
      />
      <AppButton
        onPress={() => setDraft({ showRank: !draft.showRank })}
        title={`Rank: ${draft.showRank ? 'Shown' : 'Hidden'}`}
        variant="outline"
      />
      <AppButton
        onPress={() => preview()}
        title="Preview Sample"
        variant="outline"
      />
      <AppButton
        loading={saving}
        onPress={async () => {
          if (await save(id)) navigation.goBack();
        }}
        title={id ? 'Save Template' : 'Create Template'}
      />
    </>
  );
}
export function CreateReportCardTemplateScreen({
  navigation,
  route,
}: RoleScreenProps<'CreateReportCardTemplate'>) {
  return (
    <Shell
      navigation={navigation}
      testID="create-report-card-template-screen"
      title="Create Report Card Template"
    >
      <TemplateForm navigation={navigation} schoolId={route.params.schoolId} />
    </Shell>
  );
}
export function EditReportCardTemplateScreen({
  navigation,
  route,
}: RoleScreenProps<'EditReportCardTemplate'>) {
  return (
    <Shell
      navigation={navigation}
      testID="edit-report-card-template-screen"
      title="Edit Report Card Template"
    >
      <TemplateForm
        id={route.params.templateId}
        navigation={navigation}
        schoolId={route.params.schoolId}
      />
    </Shell>
  );
}

export function ReportCardTemplateDetailsScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardTemplateDetails'>) {
  useWorkspace(route.params.schoolId);
  const load = useReportCardStore(s => s.loadTemplate);
  const item = useReportCardStore(s => s.selectedTemplate);
  useEffect(() => {
    load(route.params.templateId).catch(() => undefined);
  }, [load, route.params.templateId]);
  return (
    <Shell
      navigation={navigation}
      testID="report-card-template-details-screen"
      title="Template Details"
    >
      {item ? (
        <>
          <TemplateCard item={item} />
          {value(
            'Show component marks',
            item.showComponentMarks ? 'Yes' : 'No',
          )}
          {value('Show rank', item.showRank ? 'Yes' : 'No')}
          {value('Principal signature', item.principalSignatureLabel)}
          {value('Parent signature', item.parentSignatureLabel)}
          <AppButton
            onPress={() =>
              navigation.navigate(ROUTES.EDIT_REPORT_CARD_TEMPLATE, {
                schoolId: route.params.schoolId,
                templateId: item.id,
              })
            }
            title="Edit Template"
          />
          <AppButton
            onPress={() =>
              navigation.navigate(ROUTES.REPORT_CARD_TEMPLATE_PREVIEW, {
                schoolId: route.params.schoolId,
                templateId: item.id,
              })
            }
            title="Preview Sample"
            variant="outline"
          />
        </>
      ) : (
        <LoadingView />
      )}
    </Shell>
  );
}

export function ReportCardTemplatePreviewScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardTemplatePreview'>) {
  useWorkspace(route.params.schoolId);
  const load = useReportCardStore(s => s.loadTemplate);
  const item = useReportCardStore(s => s.selectedTemplate);
  useEffect(() => {
    if (route.params.templateId)
      load(route.params.templateId).catch(() => undefined);
  }, [load, route.params.templateId]);
  return (
    <Shell
      navigation={navigation}
      subtitle="Sample data only · no Report Card created"
      testID="report-card-template-preview-screen"
      title="Template Preview"
    >
      <AppCard style={styles.preview} variant="outlined">
        <AppText align="center" variant="heading2">
          {item?.title ?? 'Academic Report Card'}
        </AppText>
        <AppText align="center">Sample Student · Class 8 A</AppText>
        {value('Mathematics', '84 / 100 · A')}
        {value('Science', '78 / 100 · B+')}
        {value('Overall', '81.00% · A · PASS')}
        {item?.showRank !== false ? value('Rank', 2) : null}
        <AppText align="center" variant="caption">
          DEVELOPMENT PREVIEW — NOT A PDF DOCUMENT
        </AppText>
      </AppCard>
    </Shell>
  );
}

export function GenerateReportCardsScreen({
  navigation,
  route,
}: RoleScreenProps<'GenerateReportCards'>) {
  useStaffContext(route.params);
  const setDraft = useReportCardStore(s => s.setGenerationDraft);
  const draft = useReportCardStore(s => s.generationDraft);
  const preview = useReportCardStore(s => s.previewGeneration);
  const loading = useReportCardStore(s => s.isPreviewingGeneration);
  return (
    <Shell
      navigation={navigation}
      subtitle={
        route.params.sessionStatus === 'CLOSED'
          ? 'Closed Session · read-only'
          : 'Published Results only'
      }
      testID="generate-report-cards-screen"
      title="Generate Report Cards"
    >
      <AppInput
        label="Publication batch ID"
        onChangeText={publicationBatchId =>
          setDraft({
            ...(draft ?? { scope: 'COMPLETE_EXAM', templateId: '' }),
            publicationBatchId,
          })
        }
        value={draft?.publicationBatchId ?? 'publication-batch-phase13-active'}
      />
      <AppInput
        label="Active Template ID"
        onChangeText={templateId =>
          setDraft({
            ...(draft ?? {
              publicationBatchId: 'publication-batch-phase13-active',
              scope: 'COMPLETE_EXAM',
            }),
            templateId,
          })
        }
        value={draft?.templateId ?? 'report-template-standard'}
      />
      <AppButton
        onPress={() =>
          setDraft({
            publicationBatchId:
              draft?.publicationBatchId ?? 'publication-batch-phase13-active',
            templateId: draft?.templateId ?? 'report-template-standard',
            scope:
              draft?.scope === 'ONE_STUDENT' ? 'COMPLETE_EXAM' : 'ONE_STUDENT',
            studentId:
              draft?.scope === 'ONE_STUDENT' ? undefined : 'student-reyansh',
          })
        }
        title={`Scope: ${draft?.scope ?? 'COMPLETE_EXAM'}`}
        variant="outline"
      />
      <AppButton
        disabled={route.params.sessionStatus === 'CLOSED'}
        loading={loading}
        onPress={async () => {
          if (!draft)
            setDraft({
              publicationBatchId: 'publication-batch-phase13-active',
              scope: 'COMPLETE_EXAM',
              templateId: 'report-template-standard',
            });
          if (await preview())
            navigation.navigate(
              ROUTES.REPORT_CARD_GENERATION_PREVIEW,
              route.params,
            );
        }}
        title="Preview Generation"
      />
    </Shell>
  );
}

export function ReportCardGenerationPreviewScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardGenerationPreview'>) {
  useStaffContext(route.params);
  const preview = useReportCardStore(s => s.generationPreview);
  const generate = useReportCardStore(s => s.generateReportCards);
  const loading = useReportCardStore(s => s.isGeneratingReportCards);
  return (
    <Shell
      navigation={navigation}
      subtitle="Preview does not mutate data"
      testID="report-card-generation-preview-screen"
      title="Generation Preview"
    >
      {preview ? (
        <>
          <AppCard style={styles.card}>
            {value('Candidates', preview.candidateCount)}
            {value('Eligible', preview.eligibleCount)}
            {value('Existing', preview.existingCount)}
            {value('Skipped', preview.skippedCount)}
            {value('Errors', preview.errorCount)}
            {value('Expires', preview.expiresAt)}
          </AppCard>
          {preview.items.map(item => (
            <AppCard
              key={item.studentId}
              style={styles.card}
              variant="outlined"
            >
              <AppText variant="bodyMedium">{item.studentName}</AppText>
              <AppText variant="caption">
                {item.admissionNumber} · v{item.proposedVersion}
              </AppText>
              <Status
                status={
                  item.existingReportCardId
                    ? 'EXISTING'
                    : item.eligible
                    ? 'ELIGIBLE'
                    : 'SKIPPED'
                }
              />
            </AppCard>
          ))}
          <AppButton
            loading={loading}
            onPress={async () => {
              if (await generate())
                navigation.replace(
                  ROUTES.REPORT_CARD_GENERATION_RESULT,
                  route.params,
                );
            }}
            title="Commit Once"
          />
        </>
      ) : (
        <EmptyState title="Preview unavailable" />
      )}
    </Shell>
  );
}

export function ReportCardGenerationResultScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardGenerationResult'>) {
  useStaffContext(route.params);
  const result = useReportCardStore(s => s.generationResult);
  return (
    <Shell
      navigation={navigation}
      testID="report-card-generation-result-screen"
      title="Generation Result"
    >
      {result ? (
        <>
          <AppCard style={styles.card}>
            {value('Run', result.run.id)}
            {value('Status', result.run.status)}
            {value('Generated', result.run.generatedCount)}
            {value('Existing', result.run.existingCount)}
            {value('Failed', result.run.failedCount)}
          </AppCard>
          {result.items.map(item => (
            <AppCard
              key={item.studentId}
              style={styles.card}
              variant="outlined"
            >
              <AppText>{item.reportCardNumber ?? item.studentId}</AppText>
              <Status status={item.status} />
              <AppText variant="caption">{item.message}</AppText>
            </AppCard>
          ))}
        </>
      ) : (
        <EmptyState title="No generation result" />
      )}
    </Shell>
  );
}

export function ReportCardGenerationHistoryScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardGenerationHistory'>) {
  useStaffContext(route.params);
  const load = useReportCardStore(s => s.loadGenerationHistory);
  const history = useReportCardStore(s => s.generationHistory);
  useEffect(() => {
    load().catch(() => undefined);
  }, [load, route.params.examId]);
  return (
    <Shell
      navigation={navigation}
      testID="report-card-generation-history-screen"
      title="Generation History"
    >
      {history.items.length ? (
        history.items.map(item => (
          <AppCard
            key={item.id}
            onPress={() =>
              navigation.navigate(ROUTES.REPORT_CARD_GENERATION_RUN_DETAILS, {
                ...route.params,
                generationRunId: item.id,
              })
            }
            style={styles.card}
            variant="outlined"
          >
            <AppText variant="title">{item.id}</AppText>
            <Status status={item.status} />
            {value('Generated', item.generatedCount)}
            {value('Requested', item.requestedAt.slice(0, 10))}
          </AppCard>
        ))
      ) : (
        <EmptyState title="No generation history" />
      )}
    </Shell>
  );
}

export function ReportCardGenerationRunDetailsScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardGenerationRunDetails'>) {
  useStaffContext(route.params);
  const load = useReportCardStore(s => s.loadGenerationRun);
  const details = useReportCardStore(s => s.selectedGenerationRun);
  useEffect(() => {
    load(route.params.generationRunId).catch(() => undefined);
  }, [load, route.params.generationRunId]);
  return (
    <Shell
      navigation={navigation}
      testID="report-card-generation-run-details-screen"
      title="Generation Run Details"
    >
      {details ? (
        <>
          <AppCard style={styles.card}>
            {value('Run', details.run.id)}
            {value('Scope', details.run.scope)}
            {value('Status', details.run.status)}
            {value('Candidates', details.run.totalCandidates)}
          </AppCard>
          {details.items.map(item => (
            <AppCard
              key={item.studentId}
              style={styles.card}
              variant="outlined"
            >
              <AppText>{item.studentId}</AppText>
              <Status status={item.status} />
              <AppText>{item.message}</AppText>
            </AppCard>
          ))}
        </>
      ) : (
        <LoadingView />
      )}
    </Shell>
  );
}

export function ReportCardsScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCards'>) {
  useStaffContext(route.params);
  const load = useReportCardStore(s => s.loadReportCards);
  const cards = useReportCardStore(s => s.reportCards);
  const filters = useReportCardStore(s => s.reportCardFilters);
  const setFilters = useReportCardStore(s => s.setReportCardFilters);
  const loading = useReportCardStore(s => s.isLoadingReportCards);
  useEffect(() => {
    load().catch(() => undefined);
  }, [load, route.params.examId, filters]);
  return (
    <Shell
      navigation={navigation}
      testID="report-cards-screen"
      title="Report Cards"
    >
      <AppInput
        label="Search student, admission or Report Card number"
        onChangeText={search => setFilters({ page: 1, search })}
        value={filters.search ?? ''}
      />
      <AppButton
        onPress={() =>
          setFilters({
            status: filters.status === 'AVAILABLE' ? 'ALL' : 'AVAILABLE',
          })
        }
        title={`Status: ${filters.status ?? 'ALL'}`}
        variant="outline"
      />
      {loading ? (
        <LoadingView />
      ) : cards.items.length ? (
        cards.items.map(card => (
          <AppCard
            key={card.id}
            onPress={() =>
              navigation.navigate(ROUTES.REPORT_CARD_DETAILS, {
                ...route.params,
                reportCardId: card.id,
              })
            }
            style={styles.card}
            variant="outlined"
          >
            <View style={styles.between}>
              <AppText variant="title">{card.reportCardNumber}</AppText>
              <Status status={card.status} />
            </View>
            <AppText>
              {card.studentSnapshot.name} ·{' '}
              {card.studentSnapshot.admissionNumber}
            </AppText>
            <AppText variant="caption">
              {card.studentSnapshot.className}{' '}
              {card.studentSnapshot.sectionName} · v{card.version} ·{' '}
              {card.documentStatus}
            </AppText>
          </AppCard>
        ))
      ) : (
        <EmptyState title="No Report Cards" />
      )}
    </Shell>
  );
}

export function ReportCardDetailsScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardDetails'>) {
  useStaffContext(route.params);
  const load = useReportCardStore(s => s.loadReportCard);
  const card = useReportCardStore(s => s.selectedReportCard);
  const share = useReportCardStore(s => s.shareReportCard);
  useEffect(() => {
    load(route.params.reportCardId).catch(() => undefined);
  }, [load, route.params.reportCardId]);
  return (
    <Shell
      navigation={navigation}
      testID="report-card-details-screen"
      title="Report Card Details"
    >
      {card ? (
        <>
          <ReportCardView card={card} />
          <AppButton
            onPress={() =>
              navigation.navigate(ROUTES.REPORT_CARD_PREVIEW, route.params)
            }
            title="Preview / Request Document"
          />
          <AppButton
            disabled={card.status !== 'AVAILABLE'}
            onPress={() => share(card.id)}
            title="Share"
            variant="outline"
          />
          <AppButton
            onPress={() =>
              navigation.navigate(ROUTES.EXAMINATION_COMMUNICATION_HISTORY, {
                ...route.params,
                reportCardId: card.id,
              })
            }
            title="Communication History"
            variant="outline"
          />
          <AppButton
            disabled={card.status === 'REVOKED'}
            onPress={() =>
              navigation.navigate(ROUTES.REVOKE_REPORT_CARD, route.params)
            }
            title="Revoke"
            variant="danger"
          />
        </>
      ) : (
        <LoadingView />
      )}
    </Shell>
  );
}

export function ReportCardPreviewScreen({
  navigation,
  route,
}: RoleScreenProps<'ReportCardPreview'>) {
  useStaffContext(route.params);
  const loadCard = useReportCardStore(s => s.loadReportCard);
  const loadDocument = useReportCardStore(s => s.loadDocument);
  const card = useReportCardStore(s => s.selectedReportCard);
  const document = useReportCardStore(s => s.documentState);
  useEffect(() => {
    loadCard(route.params.reportCardId).catch(() => undefined);
  }, [loadCard, route.params.reportCardId]);
  return (
    <Shell
      navigation={navigation}
      subtitle="Development document abstraction"
      testID="report-card-preview-screen"
      title="Report Card Preview"
    >
      {card ? <ReportCardView card={card} /> : <LoadingView />}{' '}
      {document ? (
        <AppCard style={styles.card}>
          {value('Filename', document.filename)}
          {value('Status', document.documentStatus)}
          {value('URL', document.documentUrl)}
          <AppText variant="caption">{document.message}</AppText>
        </AppCard>
      ) : null}
      <AppButton
        loading={useReportCardStore(s => s.isLoadingDocument)}
        onPress={() => loadDocument(route.params.reportCardId)}
        title="Request Document Metadata"
      />
    </Shell>
  );
}

export function RevokeReportCardScreen({
  navigation,
  route,
}: RoleScreenProps<'RevokeReportCard'>) {
  useStaffContext(route.params);
  const [reason, setReason] = useState('');
  const revoke = useReportCardStore(s => s.revokeReportCard);
  const loading = useReportCardStore(s => s.isRevokingReportCard);
  return (
    <Shell
      navigation={navigation}
      testID="revoke-report-card-screen"
      title="Revoke Report Card"
    >
      <AppText>
        Revocation hides this version from Parent and Student access. The
        immutable record and document metadata remain in history.
      </AppText>
      <AppInput
        label="Reason"
        multiline
        onChangeText={setReason}
        required
        value={reason}
      />
      <AppButton
        disabled={!reason.trim()}
        loading={loading}
        onPress={async () => {
          if (await revoke(route.params.reportCardId, reason))
            navigation.goBack();
        }}
        title="Revoke Report Card"
        variant="danger"
      />
    </Shell>
  );
}

function setSelfContext(schoolId: string) {
  return {
    academicSessionId: '',
    branchId: '',
    examId: '',
    schoolId,
    sessionStatus: 'ACTIVE' as const,
  };
}

export function ParentResultsScreen({
  navigation,
  route,
}: RoleScreenProps<'ParentResults'>) {
  const setContext = useReportCardStore(s => s.setContext);
  const load = useReportCardStore(s => s.loadParentResults);
  const results = useReportCardStore(s => s.parentResults);
  useEffect(() => {
    setContext(setSelfContext(route.params.schoolId));
    load(route.params.parentMembershipId, route.params.studentId).catch(
      () => undefined,
    );
  }, [
    load,
    route.params.parentMembershipId,
    route.params.schoolId,
    route.params.studentId,
    setContext,
  ]);
  return (
    <Shell
      navigation={navigation}
      testID="parent-results-screen"
      title="My Results"
    >
      {results.length ? (
        results.map(item => (
          <AppCard
            key={item.publishedResultSnapshotId}
            onPress={() =>
              navigation.navigate(ROUTES.PARENT_STUDENT_RESULT_DETAILS, {
                parentMembershipId: route.params.parentMembershipId,
                publishedResultSnapshotId: item.publishedResultSnapshotId,
                schoolId: route.params.schoolId,
              })
            }
            style={styles.card}
            variant="outlined"
          >
            <AppText variant="title">{item.studentName}</AppText>
            <AppText>
              {item.examName} · {item.percentage.toFixed(2)}% ·{' '}
              {item.grade ?? item.outcome}
            </AppText>
            <AppText variant="caption">
              Published {item.publishedAt.slice(0, 10)}
              {item.reportCardAvailable ? ' · Report Card available' : ''}
            </AppText>
          </AppCard>
        ))
      ) : (
        <EmptyState title="No published Results" />
      )}
    </Shell>
  );
}
export function ParentStudentResultDetailsScreen({
  navigation,
  route,
}: RoleScreenProps<'ParentStudentResultDetails'>) {
  const setContext = useReportCardStore(s => s.setContext);
  const load = useReportCardStore(s => s.loadParentResult);
  const result = useReportCardStore(s => s.parentSelectedResult);
  useEffect(() => {
    setContext(setSelfContext(route.params.schoolId));
    load(
      route.params.parentMembershipId,
      route.params.publishedResultSnapshotId,
    ).catch(() => undefined);
  }, [
    load,
    route.params.parentMembershipId,
    route.params.publishedResultSnapshotId,
    route.params.schoolId,
    setContext,
  ]);
  return (
    <Shell
      navigation={navigation}
      testID="parent-student-result-details-screen"
      title="Result Details"
    >
      {result ? <ResultView result={result} /> : <LoadingView />}
    </Shell>
  );
}
export function ParentReportCardsScreen({
  navigation,
  route,
}: RoleScreenProps<'ParentReportCards'>) {
  const setContext = useReportCardStore(s => s.setContext);
  const load = useReportCardStore(s => s.loadParentReportCards);
  const cards = useReportCardStore(s => s.parentReportCards);
  useEffect(() => {
    setContext(setSelfContext(route.params.schoolId));
    load(route.params.parentMembershipId, route.params.studentId).catch(
      () => undefined,
    );
  }, [
    load,
    route.params.parentMembershipId,
    route.params.schoolId,
    route.params.studentId,
    setContext,
  ]);
  return (
    <Shell
      navigation={navigation}
      testID="parent-report-cards-screen"
      title="My Report Cards"
    >
      {cards.length ? (
        cards.map(card => (
          <AppCard
            key={card.id}
            onPress={() =>
              navigation.navigate(ROUTES.PARENT_REPORT_CARD_DETAILS, {
                parentMembershipId: route.params.parentMembershipId,
                reportCardId: card.id,
                schoolId: route.params.schoolId,
              })
            }
            style={styles.card}
            variant="outlined"
          >
            <AppText variant="title">{card.studentSnapshot.name}</AppText>
            <AppText>
              {card.examSnapshot.name} · {card.reportCardNumber}
            </AppText>
            <AppText variant="caption">
              Latest active version · v{card.version}
            </AppText>
          </AppCard>
        ))
      ) : (
        <EmptyState title="No available Report Cards" />
      )}
    </Shell>
  );
}
export function ParentReportCardDetailsScreen({
  navigation,
  route,
}: RoleScreenProps<'ParentReportCardDetails'>) {
  const setContext = useReportCardStore(s => s.setContext);
  const load = useReportCardStore(s => s.loadParentReportCard);
  const card = useReportCardStore(s => s.parentSelectedReportCard);
  useEffect(() => {
    setContext(setSelfContext(route.params.schoolId));
    load(route.params.parentMembershipId, route.params.reportCardId).catch(
      () => undefined,
    );
  }, [
    load,
    route.params.parentMembershipId,
    route.params.reportCardId,
    route.params.schoolId,
    setContext,
  ]);
  return (
    <Shell
      navigation={navigation}
      testID="parent-report-card-details-screen"
      title="Report Card Details"
    >
      {card ? <ReportCardView card={card} safe /> : <LoadingView />}
    </Shell>
  );
}

export function StudentResultsScreen({
  navigation,
  route,
}: RoleScreenProps<'StudentResults'>) {
  const setContext = useReportCardStore(s => s.setContext);
  const load = useReportCardStore(s => s.loadStudentResults);
  const results = useReportCardStore(s => s.studentResults);
  useEffect(() => {
    setContext(setSelfContext(route.params.schoolId));
    load(route.params.studentMembershipId).catch(() => undefined);
  }, [
    load,
    route.params.schoolId,
    route.params.studentMembershipId,
    setContext,
  ]);
  return (
    <Shell
      navigation={navigation}
      testID="student-results-screen"
      title="My Results"
    >
      {results.length ? (
        results.map(item => (
          <AppCard
            key={item.publishedResultSnapshotId}
            onPress={() =>
              navigation.navigate(ROUTES.STUDENT_SELF_RESULT_DETAILS, {
                publishedResultSnapshotId: item.publishedResultSnapshotId,
                schoolId: route.params.schoolId,
                studentMembershipId: route.params.studentMembershipId,
              })
            }
            style={styles.card}
            variant="outlined"
          >
            <AppText variant="title">{item.examName}</AppText>
            <AppText>
              {item.percentage.toFixed(2)}% · {item.grade ?? item.outcome}
            </AppText>
            <AppText variant="caption">
              Published {item.publishedAt.slice(0, 10)}
            </AppText>
          </AppCard>
        ))
      ) : (
        <EmptyState title="No published Results" />
      )}
    </Shell>
  );
}
export function StudentResultDetailsScreen({
  navigation,
  route,
}: RoleScreenProps<'StudentSelfResultDetails'>) {
  const setContext = useReportCardStore(s => s.setContext);
  const load = useReportCardStore(s => s.loadStudentResult);
  const result = useReportCardStore(s => s.studentSelectedResult);
  useEffect(() => {
    setContext(setSelfContext(route.params.schoolId));
    load(
      route.params.studentMembershipId,
      route.params.publishedResultSnapshotId,
    ).catch(() => undefined);
  }, [
    load,
    route.params.publishedResultSnapshotId,
    route.params.schoolId,
    route.params.studentMembershipId,
    setContext,
  ]);
  return (
    <Shell
      navigation={navigation}
      testID="student-result-details-screen"
      title="My Result Details"
    >
      {result ? <ResultView result={result} /> : <LoadingView />}
    </Shell>
  );
}
export function StudentReportCardsScreen({
  navigation,
  route,
}: RoleScreenProps<'StudentReportCards'>) {
  const setContext = useReportCardStore(s => s.setContext);
  const load = useReportCardStore(s => s.loadStudentReportCards);
  const cards = useReportCardStore(s => s.studentReportCards);
  useEffect(() => {
    setContext(setSelfContext(route.params.schoolId));
    load(route.params.studentMembershipId).catch(() => undefined);
  }, [
    load,
    route.params.schoolId,
    route.params.studentMembershipId,
    setContext,
  ]);
  return (
    <Shell
      navigation={navigation}
      testID="student-report-cards-screen"
      title="My Report Cards"
    >
      {cards.length ? (
        cards.map(card => (
          <AppCard
            key={card.id}
            onPress={() =>
              navigation.navigate(ROUTES.STUDENT_REPORT_CARD_DETAILS, {
                reportCardId: card.id,
                schoolId: route.params.schoolId,
                studentMembershipId: route.params.studentMembershipId,
              })
            }
            style={styles.card}
            variant="outlined"
          >
            <AppText variant="title">{card.examSnapshot.name}</AppText>
            <AppText>
              {card.reportCardNumber} · v{card.version}
            </AppText>
          </AppCard>
        ))
      ) : (
        <EmptyState title="No available Report Cards" />
      )}
    </Shell>
  );
}
export function StudentReportCardDetailsScreen({
  navigation,
  route,
}: RoleScreenProps<'StudentReportCardDetails'>) {
  const setContext = useReportCardStore(s => s.setContext);
  const load = useReportCardStore(s => s.loadStudentReportCard);
  const card = useReportCardStore(s => s.studentSelectedReportCard);
  useEffect(() => {
    setContext(setSelfContext(route.params.schoolId));
    load(route.params.studentMembershipId, route.params.reportCardId).catch(
      () => undefined,
    );
  }, [
    load,
    route.params.reportCardId,
    route.params.schoolId,
    route.params.studentMembershipId,
    setContext,
  ]);
  return (
    <Shell
      navigation={navigation}
      testID="student-report-card-details-screen"
      title="My Report Card"
    >
      {card ? <ReportCardView card={card} safe /> : <LoadingView />}
    </Shell>
  );
}

export function ResultCommunicationScreen({
  navigation,
  route,
}: RoleScreenProps<'ResultCommunication'>) {
  useStaffContext(route.params);
  const draft = useReportCardStore(s => s.communicationDraft);
  const setDraft = useReportCardStore(s => s.setCommunicationDraft);
  const preview = useReportCardStore(s => s.previewCommunication);
  const send = useReportCardStore(s => s.sendCommunication);
  const rendered = useReportCardStore(s => s.communicationPreview);
  useEffect(
    () =>
      setDraft({
        communicationType: route.params.reportCardId
          ? 'REPORT_CARD_AVAILABLE'
          : 'RESULT_PUBLISHED',
        mode: 'MANUAL_SHARE',
        publishedResultSnapshotId: route.params.publishedResultSnapshotId,
        reportCardId: route.params.reportCardId,
      }),
    [
      route.params.publishedResultSnapshotId,
      route.params.reportCardId,
      setDraft,
    ],
  );
  return (
    <Shell
      navigation={navigation}
      testID="result-communication-screen"
      title="Result Communication"
    >
      <AppInput
        label="Published Result snapshot ID"
        onChangeText={publishedResultSnapshotId =>
          setDraft({ publishedResultSnapshotId })
        }
        value={draft.publishedResultSnapshotId ?? ''}
      />
      <AppInput
        label="Report Card ID (optional)"
        onChangeText={reportCardId =>
          setDraft({ reportCardId: reportCardId || undefined })
        }
        value={draft.reportCardId ?? ''}
      />
      <AppButton
        onPress={() =>
          setDraft({
            communicationType:
              draft.communicationType === 'RESULT_PUBLISHED'
                ? 'REPORT_CARD_AVAILABLE'
                : 'RESULT_PUBLISHED',
          })
        }
        title={`Type: ${draft.communicationType ?? 'RESULT_PUBLISHED'}`}
        variant="outline"
      />
      <AppButton
        onPress={() =>
          setDraft({
            mode:
              draft.mode === 'MANUAL_SHARE' ? 'PROVIDER_SEND' : 'MANUAL_SHARE',
          })
        }
        title={`Mode: ${draft.mode ?? 'MANUAL_SHARE'}`}
        variant="outline"
      />
      <AppButton onPress={() => preview()} title="Preview Message" />
      {rendered ? (
        <AppCard style={styles.card}>
          <AppText>{rendered.renderedContent}</AppText>
          {rendered.warnings.map(item => (
            <AppText key={item} variant="caption">
              {item}
            </AppText>
          ))}
        </AppCard>
      ) : null}
      <AppButton
        disabled={!rendered}
        onPress={() => send()}
        title="Confirm Communication"
      />
    </Shell>
  );
}
export function ExaminationCommunicationHistoryScreen({
  navigation,
  route,
}: RoleScreenProps<'ExaminationCommunicationHistory'>) {
  useStaffContext(route.params);
  const load = useReportCardStore(s => s.loadCommunicationHistory);
  const history = useReportCardStore(s => s.examinationCommunicationHistory);
  useEffect(() => {
    load({
      publishedResultSnapshotId: route.params.publishedResultSnapshotId,
      reportCardId: route.params.reportCardId,
    }).catch(() => undefined);
  }, [load, route.params.publishedResultSnapshotId, route.params.reportCardId]);
  return (
    <Shell
      navigation={navigation}
      testID="examination-communication-history-screen"
      title="Examination Communication History"
    >
      {history.items.length ? (
        history.items.map(item => (
          <AppCard key={item.id} style={styles.card} variant="outlined">
            <View style={styles.between}>
              <AppText variant="title">
                {item.communicationType.replaceAll('_', ' ')}
              </AppText>
              <Status status={item.status} />
            </View>
            <AppText>
              {item.recipientName} · {item.recipientMobileMasked}
            </AppText>
            <AppText variant="caption">
              {item.createdAt} · attempt {item.attemptNumber}
            </AppText>
          </AppCard>
        ))
      ) : (
        <EmptyState title="No examination communications" />
      )}
    </Shell>
  );
}

const styles = StyleSheet.create({
  between: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  card: { marginTop: 12 },
  content: {
    alignSelf: 'center',
    gap: 10,
    maxWidth: 760,
    paddingBottom: 32,
    width: '100%',
  },
  feedback: { marginHorizontal: 16, marginTop: 10 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, padding: 12 },
  metric: { minWidth: 145, width: '47%' },
  preview: { gap: 12, marginTop: 12, paddingVertical: 18 },
  row: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 34,
  },
  rowValue: { flex: 1, marginLeft: 12, textAlign: 'right' },
  subject: {
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: 3,
    marginTop: 10,
    paddingTop: 10,
  },
  warning: { marginHorizontal: 12 },
});
