import type {
  Payment,
  PaymentReversal,
  Receipt,
  StudentAdvanceCreditEntry,
} from '../../models/collection';

const createdAt = '2026-07-30T10:00:00.000Z';

export const INITIAL_PAYMENTS: Payment[] = [
  {
    academicSessionId: 'session-school-omt-current',
    advanceAmountPaise: 50_000,
    allocatedAmountPaise: 0,
    amountPaise: 50_000,
    branchId: 'branch-main',
    collectedByName: 'Vikram Rao',
    collectedByUserId: 'user-accountant',
    createdAt,
    id: 'payment-advance-rahul',
    idempotencyKey: 'school-omt::student-rahul::fixture-advance',
    payerMobile: '9876543212',
    payerName: 'Meera Patel',
    paymentDate: '2026-07-30',
    paymentMode: 'UPI',
    paymentNumber: 'PAY/MAIN/2026-27/000001',
    receiptId: 'receipt-advance-rahul',
    referenceNumber: 'UPI-FIXTURE-001',
    schoolId: 'school-omt',
    status: 'POSTED',
    studentId: 'student-rahul',
    updatedAt: createdAt,
  },
  {
    academicSessionId: 'session-school-omt-current',
    advanceAmountPaise: 10_000,
    allocatedAmountPaise: 0,
    amountPaise: 10_000,
    branchId: 'branch-main',
    collectedByName: 'School Admin',
    collectedByUserId: 'user-school-admin',
    createdAt: '2026-07-25T10:00:00.000Z',
    id: 'payment-reversed-aarav',
    idempotencyKey: 'school-omt::student-aarav::fixture-reversed',
    paymentDate: '2026-07-25',
    paymentMode: 'CASH',
    paymentNumber: 'PAY/MAIN/2026-27/000002',
    receiptId: 'receipt-reversed-aarav',
    reversedAt: '2026-07-31T09:00:00.000Z',
    reversedByUserId: 'user-school-admin',
    reversalReason: 'Fixture correction',
    schoolId: 'school-omt',
    status: 'REVERSED',
    studentId: 'student-aarav',
    updatedAt: '2026-07-31T09:00:00.000Z',
  },
];

const schoolSnapshot = {
  address: '1, Education Road, Bhubaneswar, Odisha 751001',
  code: 'OMT001',
  mobile: '9876543200',
  name: 'OhMyTeacher Public School',
};
const branchSnapshot = {
  address: 'Education Road, Bhubaneswar, Odisha 751001',
  code: 'MAIN',
  mobile: '9876543201',
  name: 'Main Branch',
};

export const INITIAL_RECEIPTS: Receipt[] = [
  {
    academicSessionId: 'session-school-omt-current',
    advanceAmountPaise: 50_000,
    allocatedAmountPaise: 0,
    allocationSnapshots: [],
    branchId: 'branch-main',
    branchSnapshot,
    collectedByName: 'Vikram Rao',
    createdAt,
    documentStatus: 'PREVIEW_READY',
    id: 'receipt-advance-rahul',
    issuedAt: createdAt,
    payerSnapshot: { mobile: '9876543212', name: 'Meera Patel' },
    paymentAmountPaise: 50_000,
    paymentId: 'payment-advance-rahul',
    paymentMode: 'UPI',
    paymentReference: 'UPI-FIXTURE-001',
    receiptNumber: 'REC/MAIN/2026-27/000001',
    schoolId: 'school-omt',
    schoolSnapshot,
    status: 'ACTIVE',
    studentId: 'student-rahul',
    studentSnapshot: {
      admissionNumber: 'OMT-2026-0001',
      className: 'Class 1',
      name: 'Rahul Patel',
      sectionName: 'Section A',
    },
  },
  {
    academicSessionId: 'session-school-omt-current',
    advanceAmountPaise: 10_000,
    allocatedAmountPaise: 0,
    allocationSnapshots: [],
    branchId: 'branch-main',
    branchSnapshot,
    cancelledAt: '2026-07-31T09:00:00.000Z',
    cancellationReason: 'Fixture correction',
    collectedByName: 'School Admin',
    createdAt: '2026-07-25T10:00:00.000Z',
    documentStatus: 'PREVIEW_READY',
    id: 'receipt-reversed-aarav',
    issuedAt: '2026-07-25T10:00:00.000Z',
    paymentAmountPaise: 10_000,
    paymentId: 'payment-reversed-aarav',
    paymentMode: 'CASH',
    receiptNumber: 'REC/MAIN/2026-27/000002',
    schoolId: 'school-omt',
    schoolSnapshot,
    status: 'CANCELLED',
    studentId: 'student-aarav',
    studentSnapshot: {
      admissionNumber: 'OMT-2026-0002',
      className: 'Class 2',
      name: 'Aarav Kumar',
      sectionName: 'Section A',
    },
  },
];

export const INITIAL_ADVANCE_ENTRIES: StudentAdvanceCreditEntry[] = [
  {
    branchId: 'branch-main',
    createdAt,
    createdByUserId: 'user-accountant',
    creditAmountPaise: 50_000,
    debitAmountPaise: 0,
    description: 'Unapplied amount from PAY/MAIN/2026-27/000001',
    entryType: 'PAYMENT_CREDIT',
    id: 'advance-rahul-fixture',
    paymentId: 'payment-advance-rahul',
    runningBalancePaise: 50_000,
    schoolId: 'school-omt',
    studentId: 'student-rahul',
  },
  {
    branchId: 'branch-main',
    createdAt: '2026-07-25T10:00:00.000Z',
    createdByUserId: 'user-school-admin',
    creditAmountPaise: 10_000,
    debitAmountPaise: 0,
    description: 'Fixture credit',
    entryType: 'PAYMENT_CREDIT',
    id: 'advance-aarav-fixture-credit',
    paymentId: 'payment-reversed-aarav',
    runningBalancePaise: 10_000,
    schoolId: 'school-omt',
    studentId: 'student-aarav',
  },
  {
    branchId: 'branch-main',
    createdAt: '2026-07-31T09:00:00.000Z',
    createdByUserId: 'user-school-admin',
    creditAmountPaise: 0,
    debitAmountPaise: 10_000,
    description: 'Reversal of fixture credit',
    entryType: 'REVERSAL',
    id: 'advance-aarav-fixture-reversal',
    paymentId: 'payment-reversed-aarav',
    runningBalancePaise: 0,
    schoolId: 'school-omt',
    studentId: 'student-aarav',
  },
];

export const INITIAL_REVERSALS: PaymentReversal[] = [
  {
    amountPaise: 10_000,
    id: 'reversal-aarav-fixture',
    paymentId: 'payment-reversed-aarav',
    reason: 'Fixture correction',
    reversalNumber: 'REV/MAIN/2026-27/000001',
    reversedAt: '2026-07-31T09:00:00.000Z',
    reversedByName: 'School Admin',
    reversedByUserId: 'user-school-admin',
    schoolId: 'school-omt',
  },
];
