import type {
  Exam,
  ExamClassConfiguration,
  ExamSubjectPaper,
  ExamTerm,
  ExamType,
  GradeBand,
  GradingScheme,
} from '../../models/examination';
import { INITIAL_ACADEMIC_SESSIONS } from '../organization/organizationFixtures';

const now = '2026-07-15T10:00:00.000Z';
const schoolId = 'school-omt';
const branchId = 'branch-main';
const current = INITIAL_ACADEMIC_SESSIONS.find(
  item => item.id === 'session-school-omt-current',
)!;
const closed = INITIAL_ACADEMIC_SESSIONS.find(
  item => item.id === 'session-school-omt-closed',
)!;

export const INITIAL_EXAM_TERMS: ExamTerm[] = [
  {
    id: 'term-omt-current-1',
    schoolId,
    academicSessionId: current.id,
    name: 'Term 1',
    code: 'TERM1',
    startDate: current.startDate,
    endDate: `${current.startDate.slice(0, 4)}-09-30`,
    displayOrder: 1,
    status: 'ACTIVE',
    activeExamCount: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'term-omt-current-2',
    schoolId,
    academicSessionId: current.id,
    name: 'Term 2',
    code: 'TERM2',
    startDate: `${current.startDate.slice(0, 4)}-10-01`,
    endDate: current.endDate,
    displayOrder: 2,
    status: 'ACTIVE',
    activeExamCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'term-omt-closed-annual',
    schoolId,
    academicSessionId: closed.id,
    name: 'Annual Term',
    code: 'ANNUAL',
    startDate: closed.startDate,
    endDate: closed.endDate,
    displayOrder: 1,
    status: 'ACTIVE',
    activeExamCount: 1,
    createdAt: now,
    updatedAt: now,
  },
];

export const INITIAL_EXAM_TYPES: ExamType[] = [
  {
    id: 'exam-type-unit',
    schoolId,
    name: 'Unit Test',
    code: 'UNIT_TEST',
    defaultWeightagePercent: 10,
    displayOrder: 1,
    status: 'ACTIVE',
    activeExamCount: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'exam-type-half-yearly',
    schoolId,
    name: 'Half-Yearly Examination',
    code: 'HALF_YEARLY',
    defaultWeightagePercent: 30,
    displayOrder: 2,
    status: 'ACTIVE',
    activeExamCount: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'exam-type-annual',
    schoolId,
    name: 'Annual Examination',
    code: 'ANNUAL',
    defaultWeightagePercent: 60,
    displayOrder: 3,
    status: 'ACTIVE',
    activeExamCount: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'exam-type-internal-inactive',
    schoolId,
    name: 'Internal Assessment',
    code: 'INTERNAL',
    defaultWeightagePercent: 10,
    displayOrder: 4,
    status: 'INACTIVE',
    activeExamCount: 0,
    createdAt: now,
    updatedAt: now,
  },
];

const bands: GradeBand[] = [
  {
    id: 'band-a-plus',
    minimumPercentage: 90,
    maximumPercentage: 100,
    grade: 'A+',
    gradePoint: 10,
    isPassing: true,
    displayOrder: 1,
  },
  {
    id: 'band-a',
    minimumPercentage: 80,
    maximumPercentage: 89.99,
    grade: 'A',
    gradePoint: 9,
    isPassing: true,
    displayOrder: 2,
  },
  {
    id: 'band-b',
    minimumPercentage: 60,
    maximumPercentage: 79.99,
    grade: 'B',
    gradePoint: 8,
    isPassing: true,
    displayOrder: 3,
  },
  {
    id: 'band-c',
    minimumPercentage: 40,
    maximumPercentage: 59.99,
    grade: 'C',
    gradePoint: 6,
    isPassing: true,
    displayOrder: 4,
  },
  {
    id: 'band-f',
    minimumPercentage: 0,
    maximumPercentage: 39.99,
    grade: 'F',
    gradePoint: 0,
    isPassing: false,
    displayOrder: 5,
  },
];
export const INITIAL_GRADING_SCHEMES: GradingScheme[] = [
  {
    id: 'grading-omt-default',
    schoolId,
    name: 'Standard Percentage Grading',
    code: 'STANDARD',
    bands,
    isDefault: true,
    status: 'ACTIVE',
    activeExamClassCount: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'grading-omt-draft',
    schoolId,
    name: 'Primary Grades Draft',
    code: 'PRIMARY_DRAFT',
    bands: [],
    isDefault: false,
    status: 'DRAFT',
    activeExamClassCount: 0,
    createdAt: now,
    updatedAt: now,
  },
];

function config(
  examId: string,
  id: string,
  classId: string,
  className: string,
  classCode: string,
  sections: Array<{ id: string; name: string; code: string }>,
): ExamClassConfiguration {
  return {
    id,
    examId,
    schoolId,
    branchId,
    academicSessionId: current.id,
    classId,
    classNameSnapshot: className,
    classCodeSnapshot: classCode,
    sectionApplicability:
      sections.length > 1 ? 'ALL_ACTIVE_SECTIONS' : 'SELECTED_SECTIONS',
    sectionIds: sections.map(item => item.id),
    sectionSnapshots: sections,
    gradingSchemeId: 'grading-omt-default',
    gradingSchemeNameSnapshot: 'Standard Percentage Grading',
    requirePassInEverySubject: true,
    overallPassPercentage: 40,
    includeOptionalSubjectsInTotal: true,
    rankEnabled: false,
    subjectPaperCount: 1,
    totalMaximumMarks: 100,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
  };
}
export const INITIAL_EXAM_CLASS_CONFIGURATIONS: ExamClassConfiguration[] = [
  config(
    'exam-omt-complete-draft',
    'exam-config-complete-c01',
    'class-omt-c01',
    'Class 1',
    'C01',
    [
      { id: 'section-omt-c01-a', name: 'Section A', code: 'A' },
      { id: 'section-omt-c01-b', name: 'Section B', code: 'B' },
    ],
  ),
  config(
    'exam-omt-scheduled',
    'exam-config-scheduled-c02',
    'class-omt-c02',
    'Class 2',
    'C02',
    [{ id: 'section-omt-c02-a', name: 'Section A', code: 'A' }],
  ),
  config(
    'exam-omt-cancelled',
    'exam-config-cancelled-c03',
    'class-omt-c03',
    'Class 3',
    'C03',
    [{ id: 'section-omt-c03-a', name: 'Section A', code: 'A' }],
  ),
  {
    ...config(
      'exam-omt-multi-class',
      'exam-config-multi-c04',
      'class-omt-c04',
      'Class 4',
      'C04',
      [
        { id: 'section-omt-c04-a', name: 'Section A', code: 'A' },
        { id: 'section-omt-c04-b', name: 'Section B', code: 'B' },
      ],
    ),
    subjectPaperCount: 2,
    totalMaximumMarks: 200,
  },
  config(
    'exam-omt-multi-class',
    'exam-config-multi-c05',
    'class-omt-c05',
    'Class 5',
    'C05',
    [{ id: 'section-omt-c05-a', name: 'Section A', code: 'A' }],
  ),
  config(
    'exam-omt-incomplete',
    'exam-config-incomplete-c06',
    'class-omt-c06',
    'Class 6',
    'C06',
    [{ id: 'section-omt-c06-a', name: 'Section A', code: 'A' }],
  ),
];

function paper(
  examId: string,
  configurationId: string,
  id: string,
  classId: string,
  subjectId: string,
  subjectName: string,
  subjectCode: string,
  examDate: string,
  status: 'DRAFT' | 'SCHEDULED' | 'CANCELLED',
): ExamSubjectPaper {
  return {
    id,
    examId,
    examClassConfigurationId: configurationId,
    schoolId,
    branchId,
    academicSessionId: current.id,
    classId,
    subjectId,
    subjectNameSnapshot: subjectName,
    subjectCodeSnapshot: subjectCode,
    subjectTypeSnapshot: 'CORE',
    totalMaximumMarks: 100,
    totalPassMarks: 40,
    components: [
      {
        id: `${id}-theory`,
        type: 'THEORY',
        name: 'Theory',
        maximumMarks: 80,
        passMarks: 32,
        marksEntryRequired: true,
        displayOrder: 1,
      },
      {
        id: `${id}-oral`,
        type: 'ORAL',
        name: 'Oral',
        maximumMarks: 20,
        passMarks: 8,
        marksEntryRequired: true,
        displayOrder: 2,
      },
    ],
    examDate,
    startTime: '09:00',
    durationMinutes: 120,
    room: '101',
    displayOrder: 1,
    status,
    createdAt: now,
    updatedAt: now,
  };
}
export const INITIAL_EXAM_SUBJECT_PAPERS: ExamSubjectPaper[] = [
  paper(
    'exam-omt-complete-draft',
    'exam-config-complete-c01',
    'paper-complete-eng',
    'class-omt-c01',
    'subject-omt-eng',
    'English',
    'ENG',
    `${current.startDate.slice(0, 4)}-08-05`,
    'DRAFT',
  ),
  paper(
    'exam-omt-scheduled',
    'exam-config-scheduled-c02',
    'paper-scheduled-math',
    'class-omt-c02',
    'subject-omt-math',
    'Mathematics',
    'MATH',
    `${current.startDate.slice(0, 4)}-08-06`,
    'SCHEDULED',
  ),
  paper(
    'exam-omt-cancelled',
    'exam-config-cancelled-c03',
    'paper-cancelled-science',
    'class-omt-c03',
    'subject-omt-sci',
    'Science',
    'SCI',
    `${current.startDate.slice(0, 4)}-08-07`,
    'CANCELLED',
  ),
  {
    ...paper(
      'exam-omt-multi-class',
      'exam-config-multi-c04',
      'paper-multi-science',
      'class-omt-c04',
      'subject-omt-sci',
      'Science',
      'SCI',
      `${current.startDate.slice(0, 4)}-08-08`,
      'DRAFT',
    ),
    components: [
      {
        id: 'paper-multi-science-theory',
        type: 'THEORY',
        name: 'Theory',
        maximumMarks: 80,
        passMarks: 32,
        marksEntryRequired: true,
        displayOrder: 1,
      },
      {
        id: 'paper-multi-science-practical',
        type: 'PRACTICAL',
        name: 'Practical',
        maximumMarks: 20,
        passMarks: 8,
        marksEntryRequired: true,
        displayOrder: 2,
      },
    ],
  },
  {
    ...paper(
      'exam-omt-multi-class',
      'exam-config-multi-c04',
      'paper-multi-computer',
      'class-omt-c04',
      'subject-omt-comp',
      'Computer Science',
      'COMP',
      `${current.startDate.slice(0, 4)}-08-08`,
      'DRAFT',
    ),
    components: [
      {
        id: 'paper-multi-computer-internal',
        type: 'INTERNAL',
        name: 'Internal Assessment',
        maximumMarks: 100,
        passMarks: 40,
        marksEntryRequired: true,
        displayOrder: 1,
      },
    ],
    displayOrder: 2,
  },
  {
    ...paper(
      'exam-omt-multi-class',
      'exam-config-multi-c05',
      'paper-multi-math',
      'class-omt-c05',
      'subject-omt-math',
      'Mathematics',
      'MATH',
      `${current.startDate.slice(0, 4)}-08-09`,
      'DRAFT',
    ),
    components: [
      {
        id: 'paper-multi-math-theory',
        type: 'THEORY',
        name: 'Theory',
        maximumMarks: 100,
        passMarks: 40,
        marksEntryRequired: true,
        displayOrder: 1,
      },
    ],
  },
  {
    ...paper(
      'exam-omt-incomplete',
      'exam-config-incomplete-c06',
      'paper-incomplete-english',
      'class-omt-c06',
      'subject-omt-eng',
      'English',
      'ENG',
      `${current.startDate.slice(0, 4)}-08-10`,
      'DRAFT',
    ),
    components: [
      {
        id: 'paper-incomplete-english-theory',
        type: 'THEORY',
        name: 'Theory',
        maximumMarks: 90,
        passMarks: 45,
        marksEntryRequired: true,
        displayOrder: 1,
      },
    ],
    durationMinutes: undefined,
    examDate: undefined,
    startTime: undefined,
    totalPassMarks: 120,
  },
];

function exam(
  id: string,
  name: string,
  code: string,
  status: Exam['status'],
  completion: number,
): Exam {
  return {
    id,
    schoolId,
    branchId,
    academicSessionId: current.id,
    termId: 'term-omt-current-1',
    termName: 'Term 1',
    examTypeId: 'exam-type-unit',
    examTypeName: 'Unit Test',
    branchName: 'Main Branch',
    academicSessionName: current.name,
    name,
    code,
    startDate: `${current.startDate.slice(0, 4)}-08-01`,
    endDate: `${current.startDate.slice(0, 4)}-08-15`,
    defaultWeightagePercent: 10,
    status,
    classConfigurationCount: id === 'exam-omt-draft' ? 0 : 1,
    subjectPaperCount: id === 'exam-omt-draft' ? 0 : 1,
    setupCompletionPercent: completion,
    setupWarnings: [],
    ...(status === 'SCHEDULED' ? { scheduledAt: now } : {}),
    ...(status === 'CANCELLED'
      ? {
          cancellationReason: 'Fixture cancellation',
          cancelledAt: now,
          cancelledByUserId: 'user-school-admin',
        }
      : {}),
    createdAt: now,
    updatedAt: now,
  };
}
export const INITIAL_EXAMS: Exam[] = [
  exam('exam-omt-draft', 'Unit Test Draft', 'UT-DRAFT', 'DRAFT', 40),
  exam('exam-omt-complete-draft', 'Unit Test Ready', 'UT-READY', 'DRAFT', 100),
  exam(
    'exam-omt-scheduled',
    'Scheduled Unit Test',
    'UT-SCHEDULED',
    'SCHEDULED',
    100,
  ),
  {
    ...exam(
      'exam-omt-multi-class',
      'Multi-Class Assessment',
      'MULTI-CLASS',
      'DRAFT',
      80,
    ),
    classConfigurationCount: 2,
    subjectPaperCount: 3,
  },
  exam(
    'exam-omt-incomplete',
    'Incomplete Marks and Schedule',
    'INCOMPLETE',
    'DRAFT',
    60,
  ),
  exam(
    'exam-omt-cancelled',
    'Cancelled Unit Test',
    'UT-CANCELLED',
    'CANCELLED',
    100,
  ),
  {
    ...exam(
      'exam-omt-closed-history',
      'Previous Annual Examination',
      'ANNUAL-HISTORY',
      'SCHEDULED',
      100,
    ),
    academicSessionId: closed.id,
    academicSessionName: closed.name,
    termId: 'term-omt-closed-annual',
    termName: 'Annual Term',
    startDate: closed.startDate,
    endDate: closed.endDate,
  },
];

/** Stable manual-QA inputs for failures that must never live as valid records. */
export const EXAMINATION_SETUP_SCENARIOS = {
  atomicCreationFailure: { failNextAtomicCreation: true },
  crossBranchId: 'branch-greenfield-puri',
  crossSchoolId: 'school-greenfield',
  duplicateExamCode: 'UT-DRAFT',
  emptyExamContext: {
    academicSessionId: 'session-school-greenfield-current',
    branchId: 'branch-school-greenfield-main',
    schoolId: 'school-greenfield',
  },
  inactiveSectionId: 'section-omt-c01-archived',
  inactiveSubjectId: 'subject-omt-mus',
  invalidSessionId: 'session-missing',
  subjectNotAssignedToClassId: 'subject-omt-san',
} as const;
